<!doctype html public "-//w3c//dtd xhtml 1.0 transitional//en" "http://www.w3.org/tr/xhtml1/dtd/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<link rel="icon" href="/resources/favicon.ico">
<?php echo $this->headtitle(); ?>
<link href="/resources/css/style.css" rel="stylesheet" type="text/css" />
<link href="/resources/css/ui-lightness/jquery-ui-1.8.18.custom.css" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="/resources/js/jquery-1.7.1.min.js"></script>
<script type="text/javascript" src="/resources/js/jquery.scrollto.js"></script>
<script type="text/javascript" src="/resources/js/jquery-ui-1.8.18.custom.min.js"></script>
<script type="text/javascript" src="/resources/js/ui.selectmenu.js"></script>
<script type="text/javascript" src="/resources/js/scripts.js"></script>
<script type="text/javascript" src="/resources/js/jcarousellite_1.0.1.min.js"></script> 
<script type="text/javascript" src="/resources/js/jquery.floatingfixed.js"></script> 
<script type="text/javascript" src="/resources/js/jquery.timeago.js"></script> 
<script type="text/javascript" src="/resources/js/kuestyfront.js?r=<?php echo mt_rand();?>"></script> 
<style> 
	.block-large p { width: 550px !important; } 
</style>
</head>

<body style="background:none; text-align:left;">


	<div class="block-large hreview-aggregate">
		<?php $local = $this->local; ?>
		<h2><?php echo($local["nombre"]);?> <span></span></h2>
	<div id="restoId" style="display:none"><?php echo($local["id"]) ?></div>
	<div class="user-profile item">
		<img class="avatar" src="<?php if($local["logo"] == ""){ echo("http://www.kuesty.com/resources/images/no_image.png"); }else{ echo( $local["logo"]); }; ?>" alt="<?php echo($local["nombre"]);?>" width="150px;"/>
        
        	<div class="float-star">
                 <span class="stars">
					<?php for($j=1; $j <= $local["stars"]; $j++) { ?>
            		<a class="active" href=""></a>
					<?php } ?>	
					<?php for($j=0; $j < (5 -$local["stars"]); $j++) { ?>
            		<a href=""></a>
					<?php } ?>
            	</span>
            </div>
            <div class="float-star">
                <span class="dolar">
            		<?php for($j=1; $j <= $local["pesos"]; $j++) { ?>
            		<a class="active" href=""></a>
					<?php } ?>	
					<?php for($j=0; $j < (5 -$local["pesos"]); $j++) { ?>
            		<a href=""></a>
					<?php } ?>
            	</span>
            </div>
           
			<div style="display:none;"> 
				<div class="rating"><?php echo $local["stars"]; ?></div>
				<div class="price"><?php echo $local["pesos"]; ?></div>
				<div class="count"><?php echo  ((int)$local["cantidad_checkins"] + (int) $local["cantidad_reviews"]); ?></div>
			</div>

            <div class="map-road">
            	<img src="http://maps.google.com/maps/api/staticmap?center=<?php echo($local["latitud"]);?>,<?php echo($local["longitud"]);?>&size=268x143&mobile=true&format=png&sensor=false&zoom=15&markers=icon:http://kuesty.com/resources/images/map_pin.png|<?php echo($local["latitud"]);?>,<?php echo($local["longitud"]);?>" />

                <div class="clearer"></div>

			</div>
			
           
        <div class="links-user profile">
            <div class="line-break"></div>
			<a class='friends' style="padding:10px 0px 0px 15px;"><span></span><?php echo((int)$local["cant_fans"]);?> fans</a>
			<a class='tips' style="padding-top:10px;"><span></span><?php echo((int)$local["cantidad_tips"]); ?> tips</a>
			<a class='checkin' style="padding-left:15px;"><span> </span><?php echo( (int)$local["cantidad_checkins"]); ?> check-ins</a>
			<a class='review2'><span> </span><?php echo((int)$local["cantidad_reviews"]); ?> rese&ntilde;as</a>
		</div>

			 <div class="icons-food">
			<?php 
			$categorias = $local["categorias"];
			foreach($categorias as $categoria) { ?>
				<a class="<?php echo($categoria["cssClass"]); ?>" href="/restaurants/?q=&cat=<?php echo($categoria["id"]);?>" title="<?php echo($categoria["nombre"]);?>"><img src="<?php echo($categoria["imgURL"]);?>" width="36px" height="36px" alt="<?php echo($categoria["nombre"]);?>" /></a>
			<?php } ?>
		</div>
	
        <!-- a class="fan-icon" href="">Hazte fan</a -->                
    
	</div>
	
	
	<?php if($this->local["cerrado_temporalmente"]) { ?>
	<div class="horario_open">
		<img src="/resources/images/_close.png" /><a>Cerrado temporalmente</a>
	</div>
	<?php }elseif($this->horarios) { ?>
	<div class="horario_open">

		<?php if($this->open) { ?>
			<img src="/resources/images/_open.png" /><a>Abierto</a>
		<?php } else { ?>
			<img src="/resources/images/_close.png" /><a>Cerrado</a>
		<?php } ?>
	</div>
	<?php } ?>


	<div clear="both"></div>
	<br />
	<div class="address">
		<span><?php echo($local["direccion"]); ?></span>
		Tel: <?php echo($local["telefono"]); ?>
	</div>

	<div class="clearer"></div>

	<?php if($this->especial){ ?>
	<div class="checkin-special">
		<p><?php echo($this->especial["descripcion"]); ?></p>
	</div>
	<?php } ?>
   
    <a class="make-review" href="">escribir rese&Ntilde;a</a>
 
	<div class="fb-like-local">
		<iframe src="//www.facebook.com/plugins/like.php?href=<?php echo(urlencode($this->facebookURL));?>&amp;send=false&amp;layout=button_count&amp;width=450&amp;show_faces=false&amp;action=like&amp;colorscheme=light&amp;font&amp;height=35&amp;appId=150317021676268" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:450px; height:35px;" allowTransparency="true"></iframe>
	</div>
  
    
	<div class="clearer"></div>

    <div class='modal'>

	    	<h6>Ultimas rese&ntilde;as <span></span></h6>

		<?php if(count($this->reviews) == '0'){
				  echo("<span class='empty-data'>El local no tiene ninguna rese&ntilde;a todav&iacute;a</span>");
				}else{


				foreach($this->reviews as $review) { ?>

			<div class="tit-tips"><?php echo($review["titulo"]); ?> 
				<span> 
					<a href="/user/?id=<?php echo($review["id_user"]);?>&user=<?php echo($review["user"]);?>" style="float:left;">
						<img class="user-en-review" src="/user/avatar/id/<?php echo $review["id_user"] ?>" alt="<?php echo($review["user"]);?>" height="50" width="50" />
					</a>
					<div style="float:left;padding-left:5px;">
						<a style="font-size:12px;padding-bottom:3px;" href="/user/?id=<?php echo($review["id_user"]);?>&user=<?php echo($review["user"]);?>"> <?php echo($review["user"]); ?>
						</a> 
						<div style="padding-bottom:3px;"><?php echo(date("d/m/Y", strtotime($review["fecha"] .'+ 4 hours'))); ?></div>
					</div>
				</span>
			<div class="rank-dolar duplicate">
				<span class="stars">
				<?php for($j=1; $j <= $review["rating"]; $j++) { ?>
				<a class="active" href=""></a>
				<?php } ?>	
				<?php for($j=0; $j < (5 -$review["rating"]); $j++) { ?>
				<a href=""></a>
				<?php } ?>
				</span>
				<span class="dolar">
					<?php for($j=1; $j <= $review["price"]; $j++) { ?>
					<a class="active" href=""></a>
					<?php } ?>	
					<?php for($j=0; $j < (5 -$review["price"]); $j++) { ?>
					<a href=""></a>
					<?php } ?>
				</span>

			</div>
			</div>
            
            <div class="clearer separator"></div>
            
            <p style="white-space:pre-line;"><?php echo($review["comentario"]);?><br /><br /></p>
            
            <div class="clearer"></div>
            
            <!-- div class="happy-face"><span></span>123</div-->
            <!-- div class="sad-face"><span></span>4</div-->
            
            <!-- a class="flag" href=""><span></span>Denunciar</a-->
            
            <div class="clearer review-top-bar"></div>
            
			<?php }
			} ?>
    
    		<!-- button class="view-more">ver mas</button -->
    
	</div>
	<br />

    
    <div class='modal tips'>
    
    	<h4>Ultimos tips <span></span></h4>
		<?php $i = 0; ?>

		<?php if(count($this->tips) == '0'){
				  echo("<span class='empty-data'>El local no tiene calificaciones todav&iacute;a</span>");
				}else{
				foreach($this->tips as $tip) { ?>
			<div style="float:left; width:350px;">
			<div class="tit-tips">

				<img  width="75px" class='avatar' src='/user/avatar/id/<?php echo $tip["id_user"] ?>' alt="<?php echo($tip["user"]);?>" style="margin-right:15px; min-height:60px;"/>
				<a href="/user/id/<?php echo($tip["id_user"]);?>/user/<?php echo($tip["user"]);?>"><?php echo($tip["user"]); ?></a> <br /><span> <?php echo(date("d/m/Y", strtotime($tip["fecha"] .'+ 4 hours'))); ?></span></div>
            
            <div class="rank-dolar2 duplicate4">
                <span class="stars">
				<?php for($j=1; $j <= $tip["rating"]; $j++) { ?>
           		<a class="active" href=""></a>
				<?php } ?>	
				<?php for($j=0; $j < (5 -$tip["rating"]); $j++) { ?>
           		<a href=""></a>
				<?php } ?>
            	</span>
                <span class="dolar">
            		<?php for($j=1; $j <= $tip["price"]; $j++) { ?>
            		<a class="active" href=""></a>
					<?php } ?>	
					<?php for($j=0; $j < (5 -$tip["price"]); $j++) { ?>
            		<a href=""></a>
					<?php } ?>
				</span>
                
         	</div>
            
            <p style="width:260px;"><?php echo  $tip["tip"];?><br /><br /></p>
            
            <div class="clearer"></div>
            
            <!-- div class="happy-face"><span></span>123</div-->
            <!-- div class="sad-face"><span></span>4</div-->
            
            <!-- a class="flag" href=""><span></span>Denunciar</a-->
            
			</div>  
			<?php $i++; if( ($i%2) == 0) { echo '<div class="clearer"></div> <div class="clearer separator"></div>'; } ?>
             
			<?php }
				} ?>
       
    </div>
		
	</div>


</body>
</html>
