<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link rel="icon" href="/resources/favicon.ico">
<?php echo $this->headTitle(); ?>
<link href="/resources/css/style.css" rel="stylesheet" type="text/css" />
<link href="/resources/css/ui-lightness/jquery-ui-1.8.18.custom.css" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="/resources/js/jquery-1.7.1.min.js"></script>
<script type="text/javascript" src="/resources/js/jquery.scrollTo.js"></script>
<script type="text/javascript" src="/resources/js/jquery-ui-1.8.18.custom.min.js"></script>
<script type="text/javascript" src="/resources/js/ui.selectmenu.js"></script>
<script type="text/javascript" src="/resources/js/scripts.js"></script>
<script type="text/javascript" src="/resources/js/jcarousellite_1.0.1.min.js"></script> 
<script type="text/javascript" src="/resources/js/jquery.floatingFixed.js"></script> 
<script type="text/javascript" src="/resources/js/jquery.timeago.js"></script> 
<script type="text/javascript" src="/resources/js/kuestyFront.js?r=<?php echo mt_rand();?>"></script> 
<style> 
	.block-large p { width: 550px !important; } 
</style>
</head>

<body style="background:none; text-align:left;">


	<?php if(!$this->session_user["id"]) { ?>		
	<div id="avisoHome">
		<h2 style="font-size:21px;">Kuesty es una guía de bares y restos para tu smartphone.</h2>
		<p>Queres formar parte de Kuesty ? Dale LIKE a Kuesty y conecta tu cuenta para empezar a calificar los restoranes de Rosario, ganar puntos que luego vas a poder canjear por premios y ver las promociones que dan los restoranes dia a dia.</p> <br />
		<div id="fb-root" style="float:none; text-align:left;"><a href="<?php echo $this->fb_login_root; ?>"></a></div>
	</div>
	<?php }else {  ?>

	<div class="block-large" style="width:650px;margin-left:33px; text-align:left; float:none;">
	<h2>Perfil de <?php echo $this->usuario["user"];?> <span>  </span></h2>
	<div class="user-info" style="background:none;">
		<div id="contenedor_avatar" style="width:100px;">
			<div id="preview-img">
				<img class='avatar' src='/user/avatar/id/<?php echo $this->usuario["id"]?>' alt="kuesty" />
			</div>
		</div>
		<div style="display:none;" id="id_user"><?php echo $this->usuario["id"] ?></div> 
		<div class="info-user">
			<?php echo $this->usuario["nombre"]." ".substr($this->usuario["apellido"],0,1);?>. 
			<span><?php echo $this->usuario["nombre_localidad"]?>, Argentina</span>
			<span><?php echo $this->usuario["puntos"];?> puntos</span>
		</div>
		<div class="links-user">
			<a class='friends'><span></span><?php echo $this->usuario["cantidad_amigos"]?> amigos</a>
			<a class='tips'><span> </span><?php echo $this->usuario["cantidad_tips"]?> tips</a>
			<a class='checkin'><span> </span><?php echo $this->usuario["cantidad_checkins"]?> checkins</a>
			<a class='review2'><span> </span><?php echo $this->usuario["cantidad_reviews"]?> rese&ntilde;as</a>
		</div>
		<div style="float: left;margin-top: 27px;">
			<a href="http://kuesty.com/user/?id=<?php echo $this->usuario["id"]; ?>" target="_blank" class="lindo-boton">Ver perfil</a>
			<a href="http://kuesty.com/user/friends/id/<?php echo $this->usuario["id"]; ?>" target="_blank" class="lindo-boton">Buscar amigos</a>
		</div>
		<div class='clearer'></div>
	</div>
</div>
	<?php } ?>

<div class="block-large" style="width:650px;margin-left:33px;">
	<div id="comunidadSelect">
		<select id="filter" name="cat" onchange="kuesty.filterComunidad(this, true)">

			<option value="all">Todo</option>
			<!-- option value="nearby">Cerca mio</option-->
			<option value="local">Solo locales</option>
			<option value="hoy">Locales hoy</option>
			<option value="imfan">Soy Fan</option>
			<option value="friends">Mis Amigos</option>
			<option value="me">Mi actividad</option>
        </select>
	</div>
<script type="text/javascript"> $("#comunidadSelect option[value=<?php echo $this->filter; ?>]").attr("selected","selected") ;</script>
	<h2>Comunidad<span></span></h2>
	<?php if(!$this->comunidad) { ?>
	<div class="comunidad_event">
		<p><?php echo $this->error; ?></p>
	</div>
	<?php  } else { ?>
		<?php foreach($this->comunidad as $evento) { 
		$date = $evento["fecha"];
		$date = date('Y-m-d G:i:s', strtotime($date . ' + 4 hours'));	
		$evento["fecha"] = $date;
	?>
	<div class="comunidad_event"> 
		<?php if($evento["tipo"] == "newlocalbyuser") { ?>
			<a class="user_logo" href="/user/id/<?php echo $evento["id_user"];?>" target="_blank">
				<img width="75px" src="/user/avatar/id/<?php echo $evento["id_user"];?>" />
			</a>
			<a href="/user/id/<?php echo $evento["id_user"];?>" target="_blank"><?php echo $evento["nom_user"];?></a> ha agregado el local 
			<a href="/restaurants/local/id/<?php echo $evento["id_local"];?>" target="_blank" ><?php echo $evento["nom_local"];?></a> a kuesty
			<span> <script>document.write(jQuery.timeago("<?php echo $evento['fecha']; ?>"));</script></span><br />	
			<a class="local_logo" href="/restaurants/local/id/<?php echo $evento["id_local"];?>" target="_blank" >
				<img width="200px" src="/restaurants/avatar/id/<?php echo $evento["id_local"];?>" />
			</a>

		<?php }elseif($evento["tipo"] == "newuser") { ?>
			<a href="/user/id/<?php echo $evento["id_user"];?>" target="_blank"><?php echo $evento["nom_user"];?></a> se ha unido a kuesty
			<span> <script>document.write(jQuery.timeago("<?php echo $evento['fecha']; ?>"));</script></span><br />	
			<a class="friend_logo" href="/user/id/<?php echo $evento["id_user"];?>" target="_blank">
				<img width="100px" src="/user/avatar/id/<?php echo $evento["id_user"];?>" />
			</a>

		<?php }elseif($evento["tipo"] == "newcheckin" || $evento["tipo"] == "newreview") { ?>
			
			<a class="user_logo" href="/user/id/<?php echo $evento["id_user"];?>" target="_blank">
				<img width="75px" src="/user/avatar/id/<?php echo $evento["id_user"];?>" />
			</a>
			<a href="/user/id/<?php echo $evento["id_user"];?>" target="_blank"><?php echo $evento["nom_user"];?></a> 
			<?php if($evento["tipo"] == "newcheckin") { ?> ha hecho checkin en <?php } else { ?> ha escrito una rese&ntilde;a sobre <?php } ?>
			<a href="/restaurants/local/id/<?php echo $evento["id_local"];?>" target="_blank" ><?php echo $evento["nom_local"];?></a>
			<span> <script>document.write(jQuery.timeago("<?php echo $evento['fecha']; ?>"));</script> - <?php echo $evento["fecha"]; ?></span><br />		
			<a class="local_logo" href="/restaurants/local/id/<?php echo $evento["id_local"];?>" target="_blank" >
				<img width="200px" src="/restaurants/avatar/id/<?php echo $evento["id_local"];?>" />
			</a>

			<div style="float:none;" class="float-star">
                 <span class="stars">
					<?php for($j=1; $j <= $evento["stars"]; $j++) { ?>
            		<a class="active" href=""></a>
					<?php } ?>	
					<?php for($j=0; $j < (5 -$evento["stars"]); $j++) { ?>
            		<a href=""></a>
					<?php } ?>
            	</span>
            </div>
            <div style="float:none;" class="float-star">
                <span class="dolar">
            		<?php for($j=1; $j <= $evento["pesos"]; $j++) { ?>
            		<a class="active" href=""></a>
					<?php } ?>	
					<?php for($j=0; $j < (5 -$evento["pesos"]); $j++) { ?>
            		<a href=""></a>
					<?php } ?>
            	</span>
            </div>

			<p><?php echo $evento["post"]; ?><?php if($evento["tipo"] == "newreview") { ?>
	<a href="/restaurants/local/id/<?php echo $evento["id_local"];?>/name/<?php echo $evento["nom_local"];?>/rid/<?php echo $evento["id_review"];?>">
					Ver critica completa
					</a><?php } ?>
			</p>

		<?php }elseif($evento["tipo"] == "friendship") { ?>
		<?php 
			if($this->filter == "me" && $evento["id_friend"] == $this->mid) { 
				$aux["id"] = $evento["id_user"];
				$aux["nom"] = $evento["nom_user"];

				$evento["id_user"] = $evento["id_friend"];
				$evento["nom_user"] = $evento["nom_friend"];
			
				$evento["id_friend"] = $aux["id"];
				$evento["nom_friend"] = $aux["nom"];

			}
			if($this->filter == "friends" && $evento["id_user"] == $this->mid) { 

				$aux["id"] = $evento["id_user"];
				$aux["nom"] = $evento["nom_user"];

				$evento["id_user"] = $evento["id_friend"];
				$evento["nom_user"] = $evento["nom_friend"];
			
				$evento["id_friend"] = $aux["id"];
				$evento["nom_friend"] = $aux["nom"];

			}
			?>

			<a class="user_logo" href="/user/id/<?php echo $evento["id_user"];?>" target="_blank">
				<img width="75px" src="/user/avatar/id/<?php echo $evento["id_user"];?>" />
			</a>
			<a href="/user/id/<?php echo $evento["id_user"];?>" target="_blank"><?php echo $evento["nom_user"];?></a> ahora es amigo de 
			<a href="/user/id/<?php echo $evento["id_friend"];?>" target="_blank"><?php echo $evento["nom_friend"];?></a>
			<span> <script>document.write(jQuery.timeago("<?php echo $evento['fecha']; ?>"));</script></span><br />	
			<a class="friend_logo" href="/user/id/<?php echo $evento["id_friend"];?>" target="_blank">
				<img width="100px" src="/user/avatar/id/<?php echo $evento["id_friend"];?>" />
			</a>

		<?php }elseif($evento["tipo"] == "newfan") { ?>
			<a class="user_logo" href="/user/id/<?php echo $evento["id_user"];?>" target="_blank">
				<img width="75px" src="/user/avatar/id/<?php echo $evento["id_user"];?>" />
			</a>
			<a href="/user/id/<?php echo $evento["id_user"];?>" target="_blank"><?php echo $evento["nom_user"];?></a> se ha hecho fan de 
			<a href="/restaurants/local/id/<?php echo $evento["id_local"];?>" target="_blank" ><?php echo $evento["nom_local"];?></a>
			<span> <script>document.write(jQuery.timeago("<?php echo $evento['fecha']; ?>"));</script></span><br />	
			<a class="local_logo" href="/restaurants/local/id/<?php echo $evento["id_local"];?>" target="_blank" >
				<img width="200px" src="/restaurants/avatar/id/<?php echo $evento["id_local"];?>" />
			</a>

		<?php }elseif($evento["tipo"] == "newlocalstatus") { ?>

			<?php if( trim($evento["post"]) == "") {
				continue;
			} ?>
			<a class="user_logo" href="/restaurants/local/id/<?php echo $evento["id_local"];?>" target="_blank" >
				<img width="75px" src="/restaurants/avatar/id/<?php echo $evento["id_local"];?>/mobile/1" />
			</a>
			<a href="/restaurants/local/id/<?php echo $evento["id_local"];?>" target="_blank" ><?php echo $evento["nom_local"];?></a> ha actualizado su estado 
			<span> <script>document.write(jQuery.timeago("<?php echo $evento['fecha']; ?>"));</script></span><br />	
			<p style="width:530px">&ldquo;<?php echo $evento["post"]; ?>&rdquo;</p>

		<?php } ?>
	</div>
	<div class="clearer"></div>
	<?php } ?>
	<?php } ?>
</div>	
