<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link rel="icon" href="/resources/favicon.ico">
<?php echo $this->headTitle(); ?>
<link href="/resources/css/style.css" rel="stylesheet" type="text/css" />
<link href="/resources/css/ui-lightness/jquery-ui-1.8.18.custom.css" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="/resources/js/jquery-1.7.1.min.js"></script>
<script type="text/javascript" src="/resources/js/jquery.scrollTo.js"></script>
<script type="text/javascript" src="/resources/js/jquery-ui-1.8.18.custom.min.js"></script>
<script type="text/javascript" src="/resources/js/ui.selectmenu.js"></script>
<script type="text/javascript" src="/resources/js/scripts.js"></script>
<script type="text/javascript" src="/resources/js/jcarousellite_1.0.1.min.js"></script> 
<script type="text/javascript" src="/resources/js/jquery.floatingFixed.js"></script> 
<script type="text/javascript" src="/resources/js/jquery.timeago.js"></script> 
<script type="text/javascript" src="/resources/js/kuestyFront.js?r=<?php echo mt_rand();?>"></script> 
<style> 
	.block-large p { width: 550px !important; } 
</style>
</head>

<body style="background:none; text-align:left;">



<div class="block-large" style="background-color:#E3E3E3;">
	<h2>Genera tu password mobile!<span></span></h2>
	<p>Hola <b><?php echo $this->username; ?></b>, ya estas conectado a Kuesty via Facebook. <br />Ahora solo tienes que generar tu clave para empezar a usar Kuesty en tu smartphone.</p>
	<form class="contact-form" method="POST">
		<input type="password" name="password" value="" />
		<input type="password" name="password2" value="" />
		<?php if($this->form_error) { echo '<p style="color:red;">'.$this->form_error.'</p>'; } ?>
		<input type="submit" value="enviar" />
	</form>
</div>

</body>
</html>
