<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link rel="icon" href="/resources/favicon.ico">
<?php echo $this->headTitle(); ?>
<link href="/resources/css/style.css" rel="stylesheet" type="text/css" />
<link href="/resources/css/ui-lightness/jquery-ui-1.8.18.custom.css" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="/resources/js/jquery-1.7.1.min.js"></script>
<script type="text/javascript" src="/resources/js/jquery.scrollTo.js"></script>
<script type="text/javascript" src="/resources/js/jquery-ui-1.8.18.custom.min.js"></script>
<script type="text/javascript" src="/resources/js/ui.selectmenu.js"></script>
<script type="text/javascript" src="/resources/js/scripts.js"></script>
<script type="text/javascript" src="/resources/js/jcarousellite_1.0.1.min.js"></script> 
<script type="text/javascript" src="/resources/js/jquery.floatingFixed.js"></script> 
<script type="text/javascript" src="/resources/js/jquery.timeago.js"></script> 
<script type="text/javascript" src="/resources/js/kuestyFront.js?r=<?php echo mt_rand();?>"></script> 

</head>

<body style="background:none;">

	<div align="left">

		<?php if(!$this->session_user["id"]) { ?>		
	<div id="avisoHome">
		<h2 style="font-size:21px;">Kuesty es una guía de bares y restos para tu smartphone.</h2>
		<p>Queres formar parte de Kuesty ? Dale LIKE a Kuesty y conecta tu cuenta para empezar a calificar los restoranes de Rosario, ganar puntos que luego vas a poder canjear por premios y ver las promociones que dan los restoranes dia a dia.</p> <br />
		<div id="fb-root" style="float:none; text-align:left;"><a href="<?php echo $this->fb_login_root; ?>"></a></div>
	</div>
	<?php }else {  ?>

	<div class="block-large" style="width:650px;margin-left:33px; text-align:left; float:none;">
	<h2>Perfil de <?php echo $this->usuario["user"];?> <span>  </span></h2>
	<div class="user-info" style="background:none;">
		<div id="contenedor_avatar" style="width:100px;">
			<div id="preview-img">
				<img class='avatar' src='/user/avatar/id/<?php echo $this->usuario["id"]?>' alt="kuesty" />
			</div>
		</div>
		<div style="display:none;" id="id_user"><?php echo $this->usuario["id"] ?></div> 
		<div class="info-user">
			<?php echo $this->usuario["nombre"]." ".substr($this->usuario["apellido"],0,1);?>. 
			<span><?php echo $this->usuario["nombre_localidad"]?>, Argentina</span>
			<span><?php echo $this->usuario["puntos"];?> puntos</span>
		</div>
		<div class="links-user">
			<a class='friends'><span></span><?php echo $this->usuario["cantidad_amigos"]?> amigos</a>
			<a class='tips'><span> </span><?php echo $this->usuario["cantidad_tips"]?> tips</a>
			<a class='checkin'><span> </span><?php echo $this->usuario["cantidad_checkins"]?> checkins</a>
			<a class='review2'><span> </span><?php echo $this->usuario["cantidad_reviews"]?> rese&ntilde;as</a>
		</div>
		<div style="float: left;margin-top: 27px;">
			<a href="http://kuesty.com/user/?id=<?php echo $this->usuario["id"]; ?>" target="_blank" class="lindo-boton">Ver perfil</a>
			<a href="http://kuesty.com/user/friends/id/<?php echo $this->usuario["id"]; ?>" target="_blank" class="lindo-boton">Buscar amigos</a>
		</div>
		<div class='clearer'></div>
	</div>
</div>
	<?php } ?>

   <div class="searchbar" style="margin-left:0px">

            <form method="GET" action="/facebookapp/destacados">
			  	<input name="q" type="text" value="<?php echo isset($this->q) ? $this->q : 'Busca un lugar' ?>"/>
                <select id="category" name="cat">
					<option>Categoría</option>
					<?php foreach($this->categorias as $categoria) { ?>
                		<option <?php if($this->cat == $categoria['id']){ echo 'selected="selected"'; } ?> value="<?php echo $categoria["id"]; ?>" ><?php echo $categoria["nombre"]; ?></option>
					<?php } ?>
              </select>
                <input type="submit" value=""/>             
            </form>
        
        </div>

</div>

<div class="block-large" style="width:650px;margin-left:33px; text-align:left;">
	<h2><?php echo $this->titulo; ?><span></span></h2>
	
	<?php foreach($this->locales as $local) { ?>

	<a name="local-<?php echo $local['id']; ?>"></a>
	<div class="user-profile2" id="local-<?php echo $local['id'];?>">
    	<a class="thumb-locales" target="_blank" href="/restaurants/local/id/<?php echo $local["id"];?>/name/<?php echo preg_replace("/\s+/","-",$local["nombre"]);?>"> <img class='avatar' src="<?php if($local["logo"] == ""){echo ("http://www.kuesty.com/resources/images/no_image.png");}else{ echo( $local["logo"]);} ?>" alt="<?php echo $local["nombre"]?>"/></a>
        
        	<div class="tit-tips2">	
    		<a target="_blank" href="/restaurants/local/id/<?php echo $local["id"];?>/name/<?php echo preg_replace("/\s+/","-",$local["nombre"]);?>"><?php echo $local["nombre"]?> <br /><span>&nbsp;</span></a>
			</div>
            
            <div class="icons-food floating">
		<?php 
			$categorias = $local["categorias"];
			if(sizeof($categorias)) { 
				foreach($categorias as $categoria) { ?>
    				<a class="<?php echo $categoria["cssClass"]; ?>" target="_blank" href="/restaurants/?q=&cat=<?php echo $categoria["id"];?>" title="<?php echo $categoria["nombre"];?>"><img src="<?php echo $categoria["imgURL"];?>" width="36px" height="36px" alt="<?php echo $categoria["nombre"];?>" /></a>
				<?php }
			} else {
				echo '<a>&nbsp;</a>';
			} ?>
    		</div>
            
            <div class="rank-dolar duplicate3">
            		<?php echo $local["cantidad_checkins"]; ?> calificaciones
                 <span class="stars">
					<?php for($j=1; $j <= $local["stars"]; $j++) { ?>
            		<a class="active" href=""></a>
					<?php } ?>	
					<?php for($j=0; $j < (5 -$local["stars"]); $j++) { ?>
            		<a href=""></a>
					<?php } ?>
            	</span>
                <span class="dolar">
					<?php for($j=1; $j <= $local["pesos"]; $j++) { ?>
            		<a class="active" href=""></a>
					<?php } ?>	
					<?php for($j=0; $j < (5 -$local["pesos"]); $j++) { ?>
            		<a href=""></a>
					<?php } ?>
            	</span>
                
         	</div>
            
            <p class="desc">
			<?php if(strlen($local["descripcion"]) > 140) { ?>
			<?php echo substr($local["descripcion"],0,140); ?>...
			<?php } else { ?>
			<?php echo $local["descripcion"]; ?>
			<?php } ?>	
			</p>
            
            <div class="clearer-large"></div>
            
                     
    
			</div> 

					<?php } ?>
			 </div>

	
</body>
</html>
