<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link rel="icon" href="/resources/favicon.ico">
<?php echo $this->headTitle(); ?>
<link href="/resources/css/style.css" rel="stylesheet" type="text/css" />
<link href="/resources/css/ui-lightness/jquery-ui-1.8.18.custom.css" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="/resources/js/jquery-1.7.1.min.js"></script>
<script type="text/javascript" src="/resources/js/jquery.scrollTo.js"></script>
<script type="text/javascript" src="/resources/js/jquery-ui-1.8.18.custom.min.js"></script>
<script type="text/javascript" src="/resources/js/ui.selectmenu.js"></script>
<script type="text/javascript" src="/resources/js/scripts.js"></script>
<script type="text/javascript" src="/resources/js/jcarousellite_1.0.1.min.js"></script> 
<script type="text/javascript" src="/resources/js/jquery.floatingFixed.js"></script> 
<script type="text/javascript" src="/resources/js/jquery.timeago.js"></script> 
<script type="text/javascript" src="/resources/js/kuestyFront.js?r=<?php echo mt_rand();?>"></script> 

</head>

<body style="background:none;">


<div class="block fullwidth" style="width:790px;">
    
  <div class="mobile-devices" style="background-size:60% !important; top:120px; background-position:80% 0%;height:350px;"></div>
    
    	<h2>Kuesty M&oacute;vil</h2>
        
        <div class="leftside">
        
        	<img src="/resources/img/title-movil.png" />
            
            <ul>
            	<li><a target="_blank" href="http://goo.gl/NUq8r">iPhone</a></li>
                <!-- li><a onclick="alert('Muy Pronto!')" href="#">Nokia</a></li-->
                <li><a target="_blank" href="http://goo.gl/C2t3D">Android</a></li>
                <li><a target="_blank" href="http://goo.gl/UHF67">Blackberry</a></li>
                <li><a target="_blank" href="http://goo.gl/sEkg3">Blackberry OTA (*)</a></li>
				
            </ul>
        	<span>(*) Instala Kuesty directamete desde nuestros servidor si no puedes hacerlo desde el appworld </span>
        </div>
    
    </div>

	
    	
</body>
</html>
    
 
