<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link rel="icon" href="/resources/favicon.ico">
<title>Con Kuesty y Phi Phi Beach este finde safas de pagar la pizza!</title>
<link href="/resources/css/style.css" rel="stylesheet" type="text/css" />

<meta property="fb:app_id" content="537035679675226" />
<meta property="og:type" content="website"/>
<meta property="og:title" content="Con Kuesty y Phi Phi este finde safas de pagar la pizza!" />
<meta property="og:url" content="http://kuesty.com/facebookapp/phiphi" />
<meta property="og:image" content="http://kuesty.com/resources/images/promo-phiphi.fw.png" />
<meta property="og:description" content="Entra y participa del sorteo! Este finde safas de pagar la pizza!" />

<script type="text/javascript" src="/resources/js/jquery-1.7.1.min.js"></script>

</head>

<body align="center" style="text-align:center; background-image:url('http://kuesty.com/resources/img/bg-pattern.png'); background-repeat:repeat; margin-top:15px;">

<div align="center" style="border: 1px solid #bcbcbc; width:810px; padding:15px; border-radius: 8px; -moz-border-radius: 8px; background-color: #EEE; -moz-box-shadow: inset 0 0 3px #000; -webkit-box-shadow: inset 0 0 3px#000; box-shadow: inner 0 0 3px #000; background:rgba(255,255,255,0.8); margin-left: auto;
margin-right: auto; margin-bottom:20px;">
	<div style="margin-bottom:10px;">	
		<img src="http://kuesty.com/resources/images/promo-phiphi.fw.png" width="800px" />
	</div>
	<div style="width:800px;">
	<table cellspacing="0" cellpadding="0" width="100%" style="text-align:center;">
	<tbody>
		<tr>
			<td><img src="http://kuesty.com/resources/images/kuesty-promo-logo.fw.png" /></td>
			<td><img src="http://kuesty.com/resources/images/phiphi-logo.png" /></td>
		</tr>
		<tr>
			<td>
				<iframe src="//www.facebook.com/plugins/like.php?href=https%3A%2F%2Fwww.facebook.com%2Fkuestyapp&amp;send=false&amp;layout=standard&amp;width=450&amp;show_faces=true&amp;font&amp;colorscheme=light&amp;action=like&amp;height=80&amp;appId=106941089437708" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:350px; height:80px;" allowTransparency="true"></iframe>
			</td>
			<td>
				<iframe src="//www.facebook.com/plugins/like.php?href=https://www.facebook.com/pages/Parador-Viejo-Parana/173860265966926?fref=ts&amp;send=false&amp;layout=standard&amp;width=450&amp;show_faces=true&amp;font&amp;colorscheme=light&amp;action=like&amp;height=80&amp;appId=305046129613505" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:350px; height:80px;" allowTransparency="true"></iframe>
			</td>
		</tr>
		</tbody>
	</table>
	<form method="post">
		<?php if(!$this->fbpostid) { ?>

		<!--a href="<?php echo $this->fb_login;?>" id="boton-participar" class="lindo-boton" style="float:none;width: 500px; margin-top: 15px; padding-top:15px; padding-bottom:15px;">Y dale a este boton para safar de pagar la pizza!!!</a-->
		<br /><br />
		<h2>Felicitaciones Ani Perotti!!! Ganaste el concurso!!!</h2> 
		<img src="https://graph.facebook.com/612009842/picture?type=large" />

		<?php }else{ ?>
		<p  style="font-size:15px; color:#343186; padding-top:15px;">Perfecto <?php echo $this->user["first_name"]; ?> ya estas participando del sorteo de Kuesty + Parador Viejo Parana!!!<br />Estate atento, capaz que este finde safas de pagar la pizza!</p>
		<a name="#cool" href="http://kuesty.com/restaurants/local/id/764/name/Phi-Phi-Beach" class="lindo-boton" style="float:none; margin-top:20px;">Conoces el Parador Viejo Parana ??? Deja tu opinion sobre el parador en Kuesty!!!</a>			
		<script type="text/javascript">
			document.location.href="#cool";
		</script>
		<?php } ?>
	</form>
	</div>
	<?php if(sizeof($this->error)) { ?>
		<script>alert("<?php echo implode($this->error,'\n');?>")</script>
	<?php } ?>
</div>
</body>
</html>
