<script type="text/javascript">
		localStorage.setItem("nearbyPagination", 0);
		localStorage.setItem("topPagination", 0);
</script>

	<div class="block" id="nearby_guider">
    
    	<h2>Aca nomas<span></span></h2>
		<div id="map_container" style="width:99%; height:300px; border:2px solid #ccc;"></div>
		<script type="text/javascript">
		$(document).ready(function(){
			if(localStorage.getItem("geoPositionLat") == undefined) {
				navigator.geolocation.getCurrentPosition(function(geo) {
					_geo = geo;
					localStorage.setItem("geoPositionLat",geo.coords.latitude);
					localStorage.setItem("geoPositionLon",geo.coords.longitude);
					kuesty.createSearchMap(geo.coords.latitude, geo.coords.longitude);
				});			
			}else {
				kuesty.createSearchMap(localStorage.getItem("geoPositionLat"), localStorage.getItem("geoPositionLon"));
			}
		});
		</script>
		<ul id="nearbyList"></ul>

    </div>


    <!-- SECOND BLOCK -->

	<div class="block middle">
    
    	<h2>Mejor calificados<span></span></h2>
         <ul id="topList">
			<?php for($i=0; $i<sizeof($this->tops); $i++) { 
				$local = $this->tops[$i];
			?>			
        	<li>
            <a class="thumb-locales" href="/restaurants/local/id/<?php echo( $local["id"]);?>/name/<?php echo(preg_replace("/\s+/","-",$local["nombre"]));?>"><img src="<?php if($local["logo"] == ""){echo ("http://www.kuesty.com/resources/images/no_image.png");}else{ echo( $local["logo"]);}; ?>" width="105px" alt="<?php echo( $local["nombre"]);?>" /></a>
            <p>
 				<?php 
//					echo strlen($local["nombre"]); 
					$local["nombre"] = trim($local["nombre"]);
				if(strlen($local["nombre"])<20) {
						echo( $local["nombre"]); ?>
<?php }else{
						echo( substr($local["nombre"], 0, 18)."..." ); ?>
				<?php } ?>

            	<span class="rank"><?php echo( (int)$local["cantidad_checkins"]+(int)$local["cantidad_reviews"]); ?> calificaciones</span>
                <span class="stars">
					<?php for($j=1; $j <= $local["stars"]; $j++) { ?>
            		<a class="active" href=""></a>
					<?php } ?>	
					<?php for($j=0; $j < (5 -$local["stars"]); $j++) { ?>
            		<a href=""></a>
					<?php } ?>
            	</span>
                <span class="dolar">
					<?php for($j=1; $j <= $local["pesos"]; $j++) { ?>
            		<a class="active" href=""></a>
					<?php } ?>	
					<?php for($j=0; $j < (5 -$local["pesos"]); $j++) { ?>
            		<a href=""></a>
					<?php } ?>
            	</span>
				
				</p>

				<?php if($local["has_checkinespecial"]) { ?>
				<div style="clear:both"></div>
				<p class="cespecial"><?php echo $local["desc_checkin"];?></p>
				<?php } ?>

			</a>
            </li>
            <?php } ?>

        </ul>       
        <button class="view-more" onclick="kuesty.moreTop()">ver mas</button>
    
    </div>


<div class="top-users">
    <h2>+ colaboradores</h2>
    	
		<?php foreach($this->top_users as $user) { ?>
    	<div class="user local-fan-costado" onclick="document.location.href = '/user/id/<?php echo($user['id']);?>/user/<?php echo($user['user']); ?>'">
    		<img src="/user/avatar/id/<?php echo($user['id']);?>" alt="<?php echo( $user["user"]); ?>" style="width:50px;min-height:50px;"/>
    		<p><?php echo($user["user"]);?>
			<?php if( (int) $user["cantidad_reviews"]) { ?>
			<span> <?php echo((int) $user["cantidad_reviews"]);?> rese&ntilde;as</span>
			<?php } ?>
			<?php if((int) $user["cantidad_checkins"]) { ?>
			<span> <?php echo((int) $user["cantidad_checkins"]);?> checkins</span>
			<?php } ?>
			<?php if((int) $user["cantidad_tips"]) { ?>
			<span> <?php echo((int) $user["cantidad_tips"]);?> tips</span>
			<?php } ?>
			</p>
    		<div class="clearer"></div>
    	</div>
    	<?php } ?>
    	
    </div>


	<script type="text/javascript">

	guiders.createGuider({
      attachTo: "#map_container",
	  buttons: [{name: "Cerrar", onclick : guiders.hideAll }],

      description: "Es muy facil, solo arrastrando el mapa podes ir explorando toda la ciudad y encontrar en distintas zonas de la ciudad es bar or resto que estas buscando para ir. Busca algo cerca de tu casa, de donde te encuentres, en la florida, por calle pellegrini o inclisive en las islas. Kuesty, Sabes a donde ir!",
      id: "second",
      position: 1,
      title: "Explora la ciudad en busca de restos, bares, discos!"
    }).show();

	setTimeout("guiders.hideAll()", 10000);
	</script> 


