		<div id="wrapper">	
			<div id="mainCntr">
				<div id="bannerCntr">
		
					<p>Dentro de poco vas a dejar de pensar a donde podés ir a comer... lo haremos por vos!</p>
			
					<h2><span>Falta poco!</span></h2>
		
				</div>
				<div id="contenedorLogo">
					<img src="images/logo.png">
				</div>
				<div id="contentCntr">

			<!--  / LEFT CONTAINER \ -->
			<div id="leftCntr">

				<!--  / NOTIFY BOX \ -->
					<?php if(!$this->added) { ?>
					<div class="notifyBox">

						<h3 style="" class="sIFR-replaced">
						<span class="sIFR-alternate" id="sIFR_replacement_2_alternate">Si querés que te avisemos cuando lanzamos dejanos tu mail.</span></h3>
					
								
						<form enctype="application/x-www-form-urlencoded" method="post" id="form-data" action="">
		
							<fieldset>
		
								<input type="text" class="text" name="email" id="contact-email" value="">
			
								<dl style="display: none;">
									<dt>&nbsp;</dt>
									<dd><input type="hidden" name="protection" id="protection" value=""></dd>
								</dl>
		
								<div class="submit sIFR-replaced" style="">
								<span class="sIFR-alternate" id="sIFR_replacement_1_alternate">
		
									<a href="javascript:document.getElementById('form-data').submit();">Avisarme!</a>
		
								</span></div>
								<?php if($this->error) { ?>
								<p style="color:#f00;">Wops! <?php echo $this->message;  ?></p>
								<?php } ?>
						
							</fieldset>
						</form>
					</div>
					<?php }else{ ?>
					<div> 
						<h2><span class="sIFR-alternate" id="sIFR_replacement_1_alternate">	
						Kuesty llegar&aacute; pronto! Y ser&aacute;s el primero en saberlo... </div>
						</span></div></h2>
					<?php } ?>
				</div>
				<!--  / RIGHT CONTAINER \ --> 
				<div id="rightCntr"> 
 
				<!--  / FOLLOW BOX \ --> 
				<div class="followBox"> 
					
					<div class="twitter"><a href="http://www.twitter.com/kuestyapp">Seguinos en Twitter</a></div> 
					
					<div class="social"> 
						
						<h4><span>sino también por acá:</span></h4> 
						
						<ul> 
							<li><a href="https://www.facebook.com/pages/Kuesty/145597152184192" title="Facebook"><img src="images/facebook_icon.png">Facebook</a></li>
							<li><a href="https://profiles.google.com/103476601667002019989" title="Google+" class="google">Google+</a></li> 
						</ul> 
						
                       <!--div class="fb"><div id="fb-root"></div><script src="http://connect.facebook.net/en_US/all.js#appId=129405567142828&amp;xfbml=1"></script><fb:like href="http://www.facebook.com/pages/Accentuate/155518210687" send="false" layout="button_count" width="450" show_faces="false" font="trebuchet ms"></fb:like><div class="socialgp"><g:plusone></g:plusone></div></div--> 
                       
					</div> 
					
				</div> 
				<!--  \ FOLLOW BOX / --> 
				
			</div> 
			<!--  \ RIGHT CONTAINER / --> 
			</div>
		</div>


