<div class="block-large" style="width:970px;">
    
   	<h2>Terminos y condiciones<span></span></h2>
	
	<div id="terminos">

			<p class="c2"><span class="c3">Al utilizar Kuesty, el usuario acepta los siguientes t&eacute;rminos y condiciones que se detallan:</span></p>

<p class="c2"><span class="c1">Pol&iacute;tica de privacidad</span></p>
<p class="c4 c2"><span class="c1"></span></p>
<p class="c4 c2"><span class="c1"></span></p>
<p class="c2"><span class="c1">Rese&ntilde;as, checkins y tips</span></p>
<p class="c4 c2"><span class="c1"></span></p>
<p class="c2"><span class="c3">Las opiniones, votos y/o r&aacute;nkings que figuran en esta gu&iacute;a son elaborados y/o emitidos por los usuarios y no constituyen un juicio de valor por parte de Kuesty. </span></p>

<p class="c2"><span class="c3">Kuesty no asume responsabilidad alguna por las decisiones a las que arribe el receptor de la informaci&oacute;n ni por los da&ntilde;os que pudiera ocasionar la falta de exactitud de los datos asentados.</span></p>

<p class="c2"><span class="c3">Si ten&eacute;s preguntas adicionales, contactate a </span><span class="c0">info@kuesty.com</span></p>
<p class="c4 c2"><span class="c0"></span></p>
<p class="c2"><span class="c1">Checkins Especiales</span></p>
<p class="c2"><span class="c1">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></p>
<p class="c2"><span class="c3">Kuesty no garantiza el cumplimiento de las ofertas publicadas por las empresas en nuestra pagina, como as&iacute; tampoco se responsabiliza en caso de incumplimiento de las mismas por parte de las empresas oferentes ni sera responsable ante el supuesto de publicidades enga&ntilde;osas publicadas por las empresas en nuestra pagina. La funci&oacute;n de Kuesty se limita a brindar un servicio gratuito a empresas y usuarios, a fin de que los mismos logren un beneficio.</span></p>
<p class="c4 c2"><span class="c1"></span></p>
<p class="c2"><span class="c1">Comentarios</span></p>
<p class="c4 c2"><span class="c1"></span></p>
<p class="c2"><span class="c3">Los Usuarios son responsables por los comentarios y votos, debiendo mantener indemne a Kuesty ante posibles reclamos por ellos generados. Se proh&iacute;be la utilizaci&oacute;n de t&eacute;rminos ofensivos y contrarios a la moral y buenas costumbres. No se aceptar&aacute;n comentarios a modo de denuncia (ya sean sobre higiene, salubridad o impositivas) ni comentarios que mencionen nombres de personas o nombres de otros restaurantes distintos al que se est&aacute; comentando. Kuesty se reserva el derecho de no publicar, editar o borrar aquellos comentarios que a su entender violen las disposiciones de la presente pol&iacute;tica.</span></p>

<p class="c4 c2"><span></span></p>
<p class="c2"><span class="c1">Pol&iacute;ticas de privacidad y confidencialidad de la informaci&oacute;n de Kuesty</span><span class="c3">&nbsp;</span></p>

<p class="c2"><span class="c3">Este documento es parte integrante de los </span><span class="c0">T&eacute;rminos y Condiciones</span><span class="c3">&nbsp;de Kuesty. Mediante la aceptaci&oacute;n de los </span><span class="c0">T&eacute;rminos y Condiciones</span><span class="c3">&nbsp;en el momento de la registraci&oacute;n el Usuario acepta las pol&iacute;ticas aqu&iacute; contenidas.</span></p>

<p class="c2"><span class="c1">La informaci&oacute;n que recabamos</span><span class="c3">&nbsp;</span></p>

<p class="c2"><span class="c3">A los efectos de interactuar con Kuesty en el caso de calificar restaurantes y publicar comentarios, por primera vez, los usuarios deber&aacute;n proporcionar su nombre, apellido, direcci&oacute;n de correo electr&oacute;nico, nombre de usuario y contrase&ntilde;a.</span></p>

<p class="c2"><span class="c3">Se establece que en cualquier momento el usuario registrado en Kuesty podr&aacute; solicitar la baja de su solicitud y la eliminaci&oacute;n de su cuenta e informaci&oacute;n de la base de datos de Kuesty.</span></p>

<p class="c2"><span class="c3">La baja se solicitar&aacute; mediante un email mandado a </span><span class="c0">info@kuesty.com</span><span class="c3">&nbsp;DESDE LA CUENTA DE EMAIL REGISTRADA POR EL USUARIO. La cuenta se eliminar&aacute; dentro de 5 d&iacute;as del recibido del email.</span></p>

<p class="c2"><span class="c3">Kuesty recoge y almacena autom&aacute;ticamente cierta informaci&oacute;n sobre la actividad de los Usuarios y visitantes dentro de nuestro sitio web. Tal informaci&oacute;n puede incluir la URL de la que provienen (est&eacute;n o no en nuestro sitio web), a qu&eacute; URL acceden seguidamente (est&eacute;n o no en nuestro sitio web), y su localizaci&oacute;n en caso que se le haya dado el permiso correspondiente al navegador. </span></p>

<p class="c2"><span class="c1">Confidencialidad de la informaci&oacute;n</span><span class="c3">&nbsp;</span></p>
<p class="c2 c4"><span class="c3"></span></p>
<p class="c2"><span class="c3">Una vez registrado en Kuesty los datos de los Usuarios ser&aacute;n suministrados &uacute;nicamente en las formas establecidas en estas pol&iacute;ticas. Haremos todo lo que est&eacute; a nuestro alcance para proteger la privacidad de la informaci&oacute;n. Puede suceder que en virtud de &oacute;rdenes judiciales, o de regulaciones legales, nos veamos compelidos a revelar informaci&oacute;n a las autoridades o terceras partes bajo ciertas circunstancias, o bien en casos que terceras partes puedan interceptar o acceder a cierta informaci&oacute;n o transmisiones de datos en cuyo caso Kuesty no responder&aacute; por la informaci&oacute;n que sea revelada.</span></p>

<p class="c2"><span class="c3">El Usuario ser&aacute; responsable de todos los actos que tengan lugar mediante el uso de su nombre de usuario y clave, lo que incluye los perjuicios que puedan sufrir otros Usuarios y/o restaurantes que se ven perjudicados por tal motivo. Si por cualquier raz&oacute;n un Usuario creyera que alguien puede conocer su clave, deber&aacute; pedir su modificaci&oacute;n mediante un email mandado a </span><span class="c0">info@kuesty.com</span><span class="c3">&nbsp;DESDE LA CUENTA DE EMAIL REGISTRADA POR EL USUARIO. La clave se remplazar&aacute; dentro de 5 d&iacute;as de recibido el email.</span></p>


<p class="c2"><span class="c1">Uso indebido</span><span class="c3">&nbsp;</span></p>

<p class="c2"><span class="c3">En el caso que el Usuario realizara un uso indebido de la p&aacute;gina, incluyendo, pero no limitando, la realizaci&oacute;n de votos que se consideren falsos y/o tengan la intenci&oacute;n de favorecer y/o perjudicar en forma deliberada a un establecimiento, el uso indebido de la informaci&oacute;n, bajada masiva de informaci&oacute;n, utilizaci&oacute;n de palabras soeces, etc.; Kuesty se reserva el derecho de deshabilitar al Usuario, eliminar los votos realizados y eliminar los comentarios emitidos.</span></p>

<p class="c2"><span class="c1">Seguridad. Almacenamiento de la informaci&oacute;n</span><span class="c3">&nbsp;</span></p>

<p class="c2"><span class="c3">Es necesario tener muy en cuenta que la seguridad perfecta no existe en Internet.</span></p>

<p class="c2"><span class="c3">Kuesty no se hace responsable por interceptaciones ilegales o violaci&oacute;n de sus sistemas o bases de datos por parte de personas no autorizadas. Kuesty, tampoco se hace responsable por la indebida utilizaci&oacute;n de la informaci&oacute;n obtenida por esos medios.</span></p>

<p class="c2"><span class="c3">Todos los datos personales de los Usuarios ser&aacute;n almacenados en un fichero automatizado de datos personales. La base de datos respeta las condiciones de seguridad de datos establecidas por la legislaci&oacute;n, y de acuerdo a las necesidades tecnol&oacute;gicas y de seguridad de datos que se necesitan y que proveen sus proveedores de tecnolog&iacute;a y de &quot;Hosting&quot;.</span></p>

<p class="c2"><span class="c1">Derechos de modificacion de los datos personales del usuario</span><span class="c3">&nbsp;</span></p>

<p class="c2"><span class="c3">Una vez registrado en Kuesty, el Usuario podr&aacute; revisar la informaci&oacute;n entregada mediante el mail de confirmaci&oacute;n de la registraci&oacute;n y cambiar la informaci&oacute;n que nos ha enviado durante el proceso de registraci&oacute;n incluyendo la informaci&oacute;n de la registraci&oacute;n como: nombre, apellido, fecha de nacimiento, sexo, localidad.</span></p>

<p class="c2"><span class="c3">Para hacer cualquier modificaci&oacute;n en la informaci&oacute;n que fue suministrada en el momento de la Registraci&oacute;n, se debe enviar un correo electr&oacute;nico a </span><span class="c0">info@kuesty.com</span><span class="c3">&nbsp;DESDE LA DIRECCION DE EMAIL REGISTRADA POR EL USUARIO.</span></p>
<p class="c2"><span class="c3">Kuesty se adhiere a las dispocisiones correspondientes sobre la protecci&oacute;n de datos personales que se establece de manera nacional. Para mayor informaci&oacute;n: </span></p>
<p class="c2"><span class="c3 c6"><a class="c7" href="http://www.protecciondedatos.com.ar/disp102008.htm">http://www.protecciondedatos.com.ar/disp102008.htm</a></span></p>
<p class="c2"><span class="c1">Modificaciones de las Pol&iacute;ticas de Privacidad</span><span class="c3">&nbsp;</span></p>
<p class="c2"><span class="c3">Kuesty podr&aacute; modificar en cualquier momento los t&eacute;rminos y condiciones de estas Pol&iacute;ticas de Privacidad y confidencialidad y notificar&aacute; los cambios al Usuario publicando una versi&oacute;n actualizada de dichas Pol&iacute;ticas en esta secci&oacute;n informando la fecha de la &uacute;ltima actualizaci&oacute;n. </span></p>
<p class="c2"><span class="c3">Dentro de los 5 (cinco) d&iacute;as siguientes a la publicaci&oacute;n de las modificaciones introducidas, el Usuario deber&aacute; comunicar por e-mail a </span><span class="c0">info@kuesty.com.ar</span><span class="c3">&nbsp;DESDE LA DIRECCION DE e-mail REGISTRADA POR EL USUARIO.si no acepta las mismas; en ese caso quedar&aacute; disuelto el v&iacute;nculo contractual. Vencido este plazo, se considerar&aacute; que el Usuario acepta los nuevos t&eacute;rminos y las Partes continuar&aacute;n vinculadas.</span></p>
<p class="c2"><span class="c1">Jurisdicci&oacute;n y competencia</span><span class="c3">&nbsp;</span></p>
<p class="c2"><span class="c3">Para todas las cuestiones litigiosas que se susciten en relaci&oacute;n con la interpretaci&oacute;n, ejecuci&oacute;n y cumplimiento del presente acuerdo, las partes se someten a la jurisdicci&oacute;n y competencia de los Tribunales provinciales de la ciudad de Rosario. Renunciando a cualquier otro fuero o jurisdicci&oacute;n que pudiere corresponderles por cualquier raz&oacute;n presente o futura.</span></p>
<p class="c2"><span class="c3">Pol&iacute;tica vigente desde: 1 de Enero 2012</span></p>
<p class="c4 c2"><span></span></p>


	</div>	


</div>


  


