                <div class="contribuidores">
					<?php foreach($this->mejores as $k=>$v){ ?>
                    <div class="post_contribuidores" onclick="window.location.href = '/user/perfil?u='+<?php echo($v["id"]) ?>">
	                    <div class="thumb"><img src="<?php 
									if(file_exists("/resources/avatars/".$v["id"]."/".md5($v["id"])."_s.jpg")){ 
										echo("/resources/avatars/".$v["id"]."/".md5($v["id"])."_s.jpg");
									}else{ 
										echo("/resources/images/default_user.png");
									} ?>" border="0" width="60px" height="60px" /></div>
                        <div class="name"><?php echo $v["nombre"]." ".$v["apellido"]; ?></div>
                        <a class="agregar" href="#">+ Agregar</a>
                        <br clear="all" />
                    </div>
					<?php } ?>
                    <br clear="all"/>
                </div>

