<div class="titulo">
	<h2>Promos</h2>
</div>
<?php for($i=0;$i<2;$i++){ ?>
<div class="post_sponsored">
  	<div class="thumb"><img src="/resources/img_example/thumb.png" border="0"/></div>
	<div class="name">Posada del Hidalgo</div>
    <div class="rate">
        <a class="activa"></a>
        <a class="activa"></a>
        <a class="activa"></a>
        <a></a>
        <a></a>
        <br clear="all" />
    </div>
	<br clear="all" />
    <div class="texto">
    	Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris commodo nisi porttitor quam vestibulum mollis. Suspendisse turpis lacus
    </div>
</div>
<?php } ?>
