        <div id="header">
	        <div class="banda"></div>
            <div class="logo"><a href="/"></a></div>
            <br clear="all" />
            <div class="menu_aux"></div>
            <div class="search">
            	<input type="text" class="text" id="searchByString" value="Search a restaurant" onfocus="this.value='';" onBlur="if(this.value=='')this.value='Search a restaurant'"  />
                <input type="button" class="btn" onclick="kuesty.searchRestaurant();"/>
            </div>
        </div>

