<div class="titulo">
	<h2>Últimos locales</h2>
</div>
<?php foreach($this->last_locales as $k=>$v){ ?>
<div class="post_sponsored">
  	<div class="thumb"><img src=<?php if($v['logo'] == "")  echo("/resources/img_example/thumb_toprated.png"); else echo($v["logo"]); ?> height="48px" width="48px" border="0"/></div>
	<div class="name"><?php echo $v["nombre"] ?></div>
    <div class="rate">
        <a class="activa"></a>
        <a class="activa"></a>
        <a class="activa"></a>
        <a></a>
        <a></a>
        <br clear="all" />
    </div>
	<br clear="all" />
    <div class="texto">
    	<?php echo $v["descripcion"] ?>
    </div>
</div>
<?php } ?>
