  <div id="signup_form" class="block-large" style="background-color:#E3E3E3;">
    
    	<h2>Quiero registrarme y formar parte de Kuesty!<span></span></h2>
       
		<p>	Registrandote en Kuesty obtendras un bono de 20 puntos que luego podras cambiar por promociones!<br /></p>

		<p>	Si te registras a través de la aplicacion obtendras 50 puntos. <a href="/mobile"/> Quiero kuesty en mi movil!</a></p>

        <div class="contact-form">
       
		<?php if($this->sent) { ?>
			<script type="text/javascript">
				alert("Ya casi formas parte de Kuesty! Activa tu cuenta en el correo que te hemos enviado y listo!");
				document.location.href = "/user/login";
			</script>
		<?php } ?>


        	<form id="login-form" method="POST">

            	<label>Nombre</label>
                <input type="text" name="nombre" value="<?php echo $this->data['nombre'];?>"/><br />
               
		 		<label>Apellido</label>
                <input type="text" name="apellido" value="<?php echo $this->data['apellido'];?>"/><br />

				<label>E-mail</label>
                <input type="email" name="mail" value="<?php echo  $this->data['mail'];?>" /><br />

 				<label>Usuario</label>
                <input type="text" name="user" value="<?php echo $this->data['user'];?>"/><br />

				<label>Contrase&ntilde;a</label>
                <input type="password" name="pass" value=""/><br />

				<label>Repita la Contrase&ntilde;a</label>
                <input type="password" name="pass2" value=""/><br />

				<label>Sexo</label>

				<div id="radio">
					<input type="radio" id="radio1" name="radio" /><label for="radio1">Ni&ntilde;o</label>
					<input type="radio" id="radio2" name="radio" checked="checked" /><label for="radio2">Ni&ntilde;a</label>
				</div>
				<br />

				<fieldset>

					<label>Nacimiento</label>
					<label for="year" class="name-input">Día: </label>
					<select id="birth" name="dia" class="days-month" size="1">

					</select>

					<label for="month" class="name-input">Mes: </label>
					<select id="birth" name="month" class="per-month" size="1">

					</select>
					<label for="day" class="name-input">Año: </label>
					<select name="year" id="birth" class="per-year" size="1">

					</select>
				</fieldset>

				<label>Localidad</label>
                <input type="text" name="localidad_desc" value="Rosario" disabled="disabled" /><br />
				<input type="hidden" name="localidad" value="1" />

				<?php if($this->error) { ?>
					<p class="error"><?php echo $this->error; ?></p>
				<?php } ?>
				
                <input type="submit" value="Enviar" />
                <input type="reset" value="Cancelar"/>
                
            </form>
        
        </div>

        <div class="email-box"></div>


    </div>



