<?php echo $this->partial( "modules/search.phtml" ); ?>
	<div id="contenido">
	        <div class="left">
		        <div class="formulario">
				<ul id="errores_form_registro" style="color:#666"></ul>
				<form id="signup_form" action="/index/login" method="post" >
                	<div>
		    <div>
                    	<p>Nombre de usuario:</p>
                        <input name="user" type="text" />
                        <br clear="all" />
                    </div>
                	<div>
                    	<p>Contraseña:</p>
                        <input name="pass" type="password" />
                        <br clear="all" />
                    </div>
			<input type="submit" value="Enviar">
				</div>
				</form>
            </div>
            </div>
        </div>

