<script>
$(function() {
        var availableTags = [
<?php
		$listado = "";

		foreach($this->amigos as $k=>$v){
//			{ label: "Choice1", value: "value1" }
			$listado .= '{ label:\''. $v["user"] . ' - '.$v["nombre"].' '.strtoupper(substr($v["apellido"],0,1)).'\', value:\''.$v["user"].'\'},';
		}
		$listado = substr($listado,0,-1);
		echo($listado);
?>
        ];
        $( "#destinatario" ).autocomplete({
            source: availableTags
        });
    });

</script>
<div class="block-large">
	<h2>Mensajes de <?php echo $this->usuario["user"];?> <span>  </span></h2>
	<div class="user-info">
		<!-- img class='avatar' src='<?php echo $this->usuario["avatar"]?>' alt="kuesty" /-->
		<div id="contenedor_avatar" style="width:100px;">
			<div id="preview-img">
				<img class='avatar' src='/user/avatar/id/<?php echo $this->usuario["id"]?>' alt="kuesty" />
			</div>
		</div>
		<div style="display:none;" id="id_user"><?php echo $this->usuario["id"] ?></div> 
		<div class="info-user">
 			<?php echo $this->usuario["nombre"]." ".substr($this->usuario["apellido"],0,1);?>. 
			<span><?php echo $this->usuario["puntos"]?> puntos</span>
			<span><?php echo $this->usuario["nombre_localidad"]?>, Argentina</span>
		</div>
		<div class="links-user">
			<a class='friends'><span></span><?php echo $this->usuario["cantidad_amigos"]?> amigos</a>
			<a class='tips'><span> </span><?php echo $this->usuario["cantidad_tips"]?> tips</a>
			<a class='checkin'><span> </span><?php echo $this->usuario["cantidad_checkins"]?> checkins</a>
			<a class='review2'><span> </span><?php echo $this->usuario["cantidad_reviews"]?> rese&ntilde;as</a>
		</div>
       	<p><?php echo $this->usuario["descripcion"]?></p>    
    	<div class='clearer'></div>
	</div>

	<div class='modal notificaciones'>
	<?php if(!$this->conversation_error) { ?>

	<h3>Conversaci&oacute;n con <input style="font-size:14px;margin-left:10px;width:200px" type="text" id="destinatario" /> <span></span></h3>
		 
		<div class="cnv_scroll" style="height:250px !important;">
		<br />
		</div>
		<br />
		<div class="cnv_messageform">
			<textarea id="reply_textarea" onfocus="if(this.value == 'Mensaje') this.value='';">Mensaje</textarea>
			<div clear="both"></div>
			<button class="lindo-boton" style="float:none;" onclick="kuesty.sendMessage();">Enviar</button>
		</div>
				<script type="text/javascript">
				var sc = <?php echo sizeof($this->conversation); ?>* 90;
				$(".cnv_scroll").animate({ scrollTop: sc }, 1000);
				</script> 
    </div>
    
    </div>
<?php } else { ?>
	<p>No se ha podido obtener la conversacion</p>
	<a href="/messages/list/" class="lindo-boton">Volver al listado de mensajes</a>
	<br /><br />
	<br /><br />
</div>
<?php } ?>
</div>
<script>
document.getElementById("destinatario").focus();
</script>
