<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>

<meta name="description" content="Guia movil de bares y restos de Rosario. Encontrá el restaurant o bar que estabas buscando. Pubs y Restaurantes de Rosario.">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<META NAME="ROBOTS" CONTENT="INDEX, FOLLOW">
<meta property="fb:app_id" content="106941089437708" />

<?php echo $this->facebookMeta;?>
<?php echo $this->twitterMeta;?>
<link rel="icon" href="/resources/favicon.ico">
<?php echo $this->headTitle(); ?>
<link href="/resources/css/style.css" rel="stylesheet" type="text/css" />
<link href="/resources/css/ui-lightness/jquery-ui-1.8.18.custom.css" rel="stylesheet" type="text/css" />
<link rel="stylesheet" type="text/css" href="/resources/css/jquery.tagsinput.css" />
<link rel="stylesheet" media="all" type="text/css" href="/resources/css/jquery-ui-timepicker-addon.css" />

<script type="text/javascript" src="/resources/js/jquery-1.7.1.min.js"></script>
<script type="text/javascript" src="/resources/js/jquery.scrollTo.js"></script>
<script type="text/javascript" src="/resources/js/jquery-ui-1.8.18.custom.min.js"></script>
<script type="text/javascript" src="/resources/js/ui.selectmenu.js"></script>
<script type="text/javascript" src="/resources/js/scripts.js"></script>
<script type="text/javascript" src="/resources/js/jcarousellite_1.0.1.min.js"></script> 
<script type="text/javascript" src="/resources/js/jquery.floatingFixed.js"></script> 
<script type="text/javascript" src="/resources/js/jquery.timeago.js"></script> 
<script type="text/javascript" src="/resources/js/kuestyFront.js?r=<?php echo mt_rand();?>"></script> 
<script type="text/javascript" src="/resources/js/md5.js"></script> 
<script type="text/javascript" src="/resources/js/jquery.tagsinput.js"></script>

<script type="text/javascript" src="/resources/js/jquery-ui-timepicker-addon.js"></script>
<script type="text/javascript" src="/resources/js/jquery-ui-sliderAccess.js"></script>
	


<script type="text/javascript" src="/resources/js/guiders-1.3.0.js"></script>
<link rel="stylesheet" href="/resources/css/guiders-1.3.0.css" type="text/css" />

<!-- Add fancyBox main JS and CSS files -->
	<script type="text/javascript" src="/resources/js/fancybox/jquery.fancybox.js?v=2.1.0"></script>
	<link rel="stylesheet" type="text/css" href="/resources/js/fancybox/jquery.fancybox.css?v=2.1.0" media="screen" />

<script type="text/javascript" src="http://maps.google.com/maps/api/js?libraries=geometry&sensor=false"></script>

<!-- start Mixpanel --><script type="text/javascript">(function(e,b){if(!b.__SV){var a,f,i,g;window.mixpanel=b;a=e.createElement("script");a.type="text/javascript";a.async=!0;a.src=("https:"===e.location.protocol?"https:":"http:")+'//cdn.mxpnl.com/libs/mixpanel-2.2.min.js';f=e.getElementsByTagName("script")[0];f.parentNode.insertBefore(a,f);b._i=[];b.init=function(a,e,d){function f(b,h){var a=h.split(".");2==a.length&&(b=b[a[0]],h=a[1]);b[h]=function(){b.push([h].concat(Array.prototype.slice.call(arguments,0)))}}var c=b;"undefined"!==
typeof d?c=b[d]=[]:d="mixpanel";c.people=c.people||[];c.toString=function(b){var a="mixpanel";"mixpanel"!==d&&(a+="."+d);b||(a+=" (stub)");return a};c.people.toString=function(){return c.toString(1)+".people (stub)"};i="disable track track_pageview track_links track_forms register register_once alias unregister identify name_tag set_config people.set people.increment people.append people.track_charge people.clear_charges people.delete_user".split(" ");for(g=0;g<i.length;g++)f(c,i[g]);b._i.push([a,
e,d])};b.__SV=1.2}})(document,window.mixpanel||[]);
mixpanel.init("147cf3e28614fd0afe0e77286906f8fe");</script><!-- end Mixpanel -->

<?php echo $this->mixpanel_user; ?>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-32842001-1']);
  _gaq.push(['_trackPageview']);

   (function() {
     var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
	     ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
	     var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
   })();

</script>

<!-- Google Tag Manager -->
<noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-K6VJ"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-K6VJ');</script>
<!-- End Google Tag Manager -->

<?php echo $this->headScript(); ?>
<!--[if lt IE 9]>
    <style>
        body {
            background-image: url(../img/bg-standard3.png) !important;
            background-repeat: repeat-x !important;
            background-position: center top !important;
        }
    </style>
<![endif]-->

</head>

<body>

	
	<!--div class="sorteo" style="display:none; ;text-align:center;">
		<img src="http://4.bp.blogspot.com/-wvpOXuvDs6M/UeAhJxArCII/AAAAAAAAMtM/8jUiY5tGMmw/s1600/friends.png" width="600px" height="400px";>
		<button class="lindo-boton" style="float:none;margin-left:auto;margin-right:auto;">A ver donde puedo ir el Dia del Amigo!</button>
	</div-->

<script>

	
	if(window.localStorage.getItem("neilarmstrong")== null) {
		window.localStorage.setItem("neilarmstrong",1);
		$(document).ready(function() {
			$('.sorteo').fancybox();
			$('.sorteo').show();   
			$(".sorteo").find('button, img').click(function(){
				window.open('http://kuestyapp.blogspot.com.ar/2013/07/cena-dia-del-amigo-aca-les-dejamos-las.html', "_blank")
			});
			$(".sorteo").fancybox().trigger('click');
		});
	}
	
	</script>


	<div class="loading_modal">pensando...</div>

	<div id="dialog-message" style="display:none;text-align:left;" title="Kuesty dice:">
  		<p></p>
	</div>

	<div id="social">
		<div><a target="_blank" href="https://www.facebook.com/kuestyapp"><img src="/resources/images/facebook.png" /></a></div>
		<div><a target="_blank" href="https://www.twitter.com/kuestyapp"><img src="/resources/images/twitter.png" /></a></div>
	</div>
	<script> $('#social').floatingFixed({ padding: 5 }); </script>


	<div id="content">
	
    <div class="header">
    
    	<ul>
        	<li><a <?php if($this->seccion == "home"){ echo 'class="active"'; } ?> href="/">Home</a></li>
            <li><a <?php if($this->seccion == "restaurants"){ echo 'class="active"'; } ?> href="/restaurants">Restaurantes</a></li>
            <li><a <?php if($this->seccion == "mobile"){ echo 'class="active"'; } ?> href="/mobile">Kuesty Móvil</a></li>
        </ul>
        
        <div class="logo">
        	<h1><a href="/">Kuesty</a></h1>
        </div>
		
		<?php 
			$session = $this->session_user;
			if(!(int)$session["id"]) { ?>
        <div class="links">
        	<a href="/user/login">login</a>
            <a href="/signup">sign up</a>
		</div>
			<div id="fb-root-top">
			<a href="<?php echo $this->fb_login_root; ?>"></a>
			</div>
		<?php } else { ?>
		<div class="menu-user">
        	<a href="/user/?id=<?php echo $session["id"];?>&user=<?php echo $session['user'];?>"><img src="<?php echo $session["avatar"];?>" alt="<?php echo $session["user"];?>" />
			<div class="user-name"><?php echo $session["user"];?> &nbsp; &nu;</div>
			<?php if($this->notif_unread != 0){ ?>
			</a><div class="badge"><?php echo $this->notif_unread; ?></div>
			<?php } ?>
			<div class="clearer"></div>
            <ul>
                <li><a href="/user/notifications/" title="Notificaciones de <?php echo $session["user"];?>"> Notificaciones</a></li>
                <li><a href="/messages/list/" title="Mensajes de <?php echo $session["user"];?>"> Mensajes</a></li>
                <li><a href="/user/logout"> Cerrar session</a></li>
            </ul>
      	</div>
		<?php } ?>	
    
    	<div class="clearer"></div>

		<a id="comunidad" href="/comunidad">Comunidad</a>		

        <div class="searchbar" style="height:70px;">

            <form method="GET" action="/restaurants">
			  	<input name="q" type="text" value="<?php echo isset($this->q) ? $this->q : 'Busca un lugar' ?>"/>
                <select id="category" name="cat">
					<option>Categoría</option>
					<?php foreach($this->categorias as $categoria) { ?>
                		<option <?php if($this->cat == $categoria['id']){ echo 'selected="selected"'; } ?> value="<?php echo $categoria["id"]; ?>" ><?php echo $categoria["nombre"]; ?></option>
					<?php } ?>
              </select>
                <input type="submit" value=""/>             
			</form>
			<div id="advanced-search" style="display:none;">aaaaa</div>
			<ul class="tabrow" onclick="$('#advanced-search').toggle()" style="display:none;">
   			 	<li style="margin-top:15px;margin-right:15px;">Avanzada</li>
			</ul>
        </div>
    
    </div>
	<?php if(!$this->session_user["id"] && $this->seccion == "home"){ ?>
	<div id="avisoHome">
			<h2>Kuesty es una guía de bares y restos para tu smartphone.</h2>
			<p>Llegó KUESTY, la aplicación para tu móvil que te permite localizar el bar, pub o resto que prefieras, su calificación en un ranking, conocer los mejores platos de cada uno, la distancia a la que estás en este momento y muchos servicios más! Bajatela y empeza a disfrutarla ya.</p>
			<button onclick="document.location.href='/user/login'" class="lindo-boton">Crear una cuenta de Kuesty</button><button onclick="document.location.href='/mobile'" class="lindo-boton">Descargar a mi cel</button>
	</div>
	<div class="clearer"></div>
	<?php } ?>


    <?php echo $this->layout()->content ?>
	
</div>

	<div class="footer">
		<div class="wrapper-footer">
			<a class="logo-urucas" href="http://urucas.com" target="_blank"></a>
    		<div class="logo-footer"></div>
    	
    		<ul>
    			<li><a href="/">Principal</a></li>
    			<li><a href="/restaurants">Restaurantes</a></li>
    			<li><a href="/comunidad">Comunidad</a></li>
    			<li><a href="http://kuestyapp.blogspot.com.ar/" target="_blank">Blog</a></li>
    			<li><a href="/mobile">Movil</a></li>
    			<li><a href="/user/login">Login</a></li>
    			<li><a href="/signup">Registro</a></li>
    			<li><a href="/contact">Contacto</a></li>
    			<li><a href="/premios">Premios</a></li>
    			<li><a href="/premios">Ayuda</a></li>
    			<li><a href="/terminos">Terminos y Condiciones</a></li>
    		</ul>
    	
    		<div class="clearer"></div>
		</div>   	
	</div>

	<?php if($this->seccion != "mobile") { ?>
	<div id="mobile_download" onclick="document.location.href='/mobile'">
		<div id="mobile_social" style="float:right; padding-top:25px;padding-rightt:10px;">
			<iframe src="//www.facebook.com/plugins/like.php?href=http%3A%2F%2Ffacebook.com%2Fkuestyapp&amp;send=false&amp;layout=button_count&amp;width=450&amp;show_faces=false&amp;font&amp;colorscheme=light&amp;action=recommend&amp;height=21&amp;appId=537035679675226" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:130px; height:21px;" allowTransparency="true"></iframe><br />
<a href="https://twitter.com/kuestyapp" class="twitter-follow-button" data-show-count="false" data-lang="es" data-dnt="true">Seguir a @kuestyapp</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
		</div>

		<div class="mobiles_img"><img src="http://kuesty.com/resources/img/mobile-devices.png" height="80px" width="auto" /></div>
		<div class="mobile_text">
			<p>Todavia no descargaste Kuesty en tu movil ? Que estas esperando!</p>
		</div>
	</div>
	<script type="text/javascript">
	$(function() {        
		//  	$("#mobile_download").floatingFixed();
		//
		//  	
		$(document).ready(function(){

			
			var set = $(window).height() - 85;
   			$('#mobile_download').animate({top:set},{duration:500,queue:false});

			$(window).scroll(function () {
				var set = $(window).height() - 85;
				$('#mobile_download').animate({top:set},{duration:500,queue:false});

				var _top = $(window).scrollTop() + $(window).height() - 90;

				if(_top >= ( $(document).height() - 100)) {
					$("#mobile_download").hide();
				}else {
					$("#mobile_download").show();
				}
		    });
		});
	
		// setTimeout('$("#mobile_download").fadeOut();',8000);
    });
	</script>
	<?php } ?>

	<script>
		$("body").on({
    		// When ajaxStart is fired, add 'loading' to body class
			ajaxStart: function() {
			   	$(this).addClass("loading"); 
    		},
    		// When ajaxStop is fired, rmeove 'loading' from body class
    		ajaxStop: function() { 
        		$(this).removeClass("loading"); 
    		}    
		});
		
	</script>


				


</body>
</html>
