<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"  dir="ltr" lang="en-US">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>Backend Prolab</title>
    <link rel="shortcut icon" href="../../img/favicon.ico" />

    <!-- jQuery y UI  con sus estilos y todo-->
	
    <script type="text/javascript" src="../../js/jquery-1.4.3.min.js"></script>
    <script type="text/javascript" src="../../js/jquery-ui-1.8.6.custom.min.js"></script>
    <script type="text/javascript" src="../../js/jquery.path.js"></script>


    <!-- Pam -->
    <script src="../../js/prolab.js" type="text/javascript"></script>
    <script type="text/javascript">
        $(document).ready(function(){
        	//Calendar para fechas mas actuales
        	$('.datepicker_actual').datepicker({ changeYear: true,changeMonth: true,yearRange: '1980:2010', dateFormat: 'yy-mm-dd' });
        });
    </script>
    <link type="text/css" rel="stylesheet" href="../../js/css/overcast/jquery-ui-1.8.6.custom.css" />

    <link type="text/css" rel="stylesheet" href="../../css/load-styles.css" />
    <link type="text/css" rel="stylesheet" href="../../css/back-color.css" />
    <link type="text/css" rel="stylesheet" href="../../css/backend.css" />
</head>
<body class="wp-admin no-js  index-php">
<div id="wpwrap">
<div id="wpcontent">
<div id="wphead">

<a href="/backend/index" title="Visit Site"><img id="header-logo" src="../../img/logo_footer.png" alt="Prolab" width="129" height="60" /></a>

<div id="wphead-info">
<div id="user_info">
    <p>Bienvenido, <b>admin</b> | <a href="/backend/logout" title="Log Out">Log Out</a></p>
</div>

<!-- Para las traducciones
<div id="favorite-actions">
	<div id="favorite-first"><a href="post-new.php">New Post</a></div><div id="favorite-toggle"><br /></div><div id="favorite-inside"><div class='favorite-action'><a href='edit.php?post_status=draft'>Drafts</a></div>
	<div class='favorite-action'><a href='post-new.php?post_type=page'>New Page</a></div>
	<div class='favorite-action'><a href='media-new.php'>Upload</a></div>
	<div class='favorite-action'><a href='edit-comments.php'>Comments</a></div>
	</div>
</div-->

</div>
</div>

<div id="wpbody">
