<ul id="adminmenu">

	<li class="wp-first-item wp-has-submenu wp-has-current-submenu wp-menu-open menu-top menu-top-first menu-icon-dashboard menu-top-last" id="menu-dashboard">
		<div class='wp-menu-image'><a href='/backend/index'><br /></a></div><a href='/backend/index' class="wp-first-item wp-has-submenu wp-has-current-submenu wp-menu-open menu-top menu-top-first menu-icon-dashboard menu-top-last" tabindex="1">Inicio</a>
		<div class='wp-submenu'><div class='wp-submenu-head'>Inicio</div><ul><li class="wp-first-item current"><a href='/backend/index' class="wp-first-item current" tabindex="1">Panel</a></li></ul></div>
	</li>
	<li class="wp-menu-separator"><a class="separator" href="?unfoldmenu=1"><br /></a></li>
	<li class="wp-has-submenu menu-icon-post menu-top-first" id="menu-posts">
		<div class='wp-menu-image'><a href=''><br /></a></div>
		<a href='' class="wp-has-submenu menu-top menu-icon-post menu-top-first" tabindex="1">ABM's Usr</a>
		<div class='wp-submenu'>
			<ul>
				<li class="wp-first-item"><a href='/backend/listar?table=puestos' class="wp-first-item" tabindex="1">Puestos</a></li>
				<li><a href='/backend/listar?table=areas' tabindex="1">Areas</a></li>
			</ul>
		</div>
	</li>
	<li class="menu-top menu-icon-post">
		<div class='wp-menu-image'><a href=''><br /></a></div>
		<a href='' class="menu-top menu-icon-post" tabindex="1">ABM's Emp</a>
		<div class='wp-submenu'>
			<ul>
                    <li class="wp-first-item"><a href='/backend/listar?table=actividad_emp' class="wp-first-item" tabindex="1">Actividad</a></li>
				<li><a href='/backend/listar?table=dotacion_emp' tabindex="1">Dotación</a></li>
				<li><a href='/backend/listar?table=iva_emp' tabindex="1">Iva</a></li>
			</ul>
		</div>
	</li>
	<li class="menu-top menu-icon-post">
		<div class='wp-menu-image'><a href=''><br /></a></div>
		<a href='' class="menu-top menu-icon-post" tabindex="1">ABM's </a>
		<div class='wp-submenu'>
			<ul>
				<li class="wp-first-item">
				<li><a href='/backend/listar?table=localidades' tabindex="1">Provincias/Zonas</a></li>
				<li><a href='/backend/listar?table=paises' tabindex="1">Paises</a></li>
				<li class="wp-last-item"><a href='/backend/listar?table=planes' tabindex="1">Planes</a></li>
			</ul>
		</div>
	</li>
    <li class="menu-top menu-icon-post">
		<div class='wp-menu-image'><a href=''><br /></a></div>
		<a href='' class="menu-top menu-icon-post" tabindex="1">ABM's Tablero</a>
		<div class='wp-submenu'>
			<ul>
				<li class="wp-first-item">
				<li><a href='/backend/listar?table=indicadores' tabindex="1">Indicadores</a></li>
				<li><a href='/backend/listar?table=objetivos_tc' tabindex="1">Objetivos</a></li>
				<li class="wp-last-item"><a href='/backend/listar?table=reales_tc' tabindex="1">Reales</a></li>
			</ul>
		</div>
	</li>
	<li class="wp-menu-separator"><a class="separator" href="?unfoldmenu=1"><br /></a></li>

	<li class="wp-has-submenu menu-top menu-icon-users menu-top-first" id="menu-users">
		<div class='wp-menu-image'><a href=''><br /></a></div><div class="wp-menu-toggle"><br /></div><a href='' class="wp-has-submenu menu-top menu-icon-users menu-top-first" tabindex="1">Usuarios</a>
		<div class='wp-submenu'><div class='wp-submenu-head'>Usuarios</div>
			<ul>
				<li class="wp-first-item"><a href='/backend/listar?table=usuarios' class="wp-first-item" tabindex="1">Usuarios</a></li>
				<li><a href='#' tabindex="1"></a></li>
			</ul>
		</div>
	</li>

	<li class="wp-has-submenu menu-top menu-icon-emp" id="menu-emp">
		<div class="wp-menu-image-emp"><a href=''><br /></a></div><div class="wp-menu-toggle"><br /></div><a href='' class="wp-has-submenu menu-top menu-icon-users" tabindex="1">Empresas</a>
		<div class='wp-submenu'><div class='wp-submenu-head'>Empresas</div>
			<ul>
				<li class="wp-first-item"><a href='/backend/listar?table=empresas' class="wp-first-item" tabindex="1">Empresas</a></li>
				<li><a href='/backend/listar?table=propuestas' tabindex="1">Propuestas</a></li>
				<li class="wp-last-item"><a href='/backend/listar?table=proyectos' tabindex="1">Proyectos</a></li>
			</ul>
		</div>
	</li>

	<li class="wp-menu-separator"><a class="separator" href="?unfoldmenu=1"><br /></a></li>

	<li class="wp-has-submenu menu-top menu-icon-settings menu-top-first" id="menu-settings">
		<div class='wp-menu-image'><a href=''><br /></a></div><div class="wp-menu-toggle"><br /></div><a href='' class="wp-has-submenu menu-top menu-icon-settings menu-top-last" tabindex="1">Tablero de control</a>
		<div class='wp-submenu'><div class='wp-submenu-head'></div>
			<ul>
				<li class="wp-first-item"><a href='/backend/tablero' class="wp-first-item" tabindex="1">Gerencial</a></li>
				<li class="wp-last-item"><a href='/backend/tablero' tabindex="1">Operativo</a></li>

			</ul>
		</div>
	</li>

    <li class="wp-menu-separator"><a class="separator" href="?unfoldmenu=1"><br /></a></li>

	<li class="wp-has-submenu menu-top menu-icon-page menu-top-first" id="menu-settings">
		<div class='wp-menu-image'><a href='/backend/bitacora'><br /></a></div><div class="wp-menu-toggle"><br /></div><a href='/backend/bitacora' class="wp-has-submenu menu-top menu-icon-settings menu-top-last" tabindex="1">Bitácoras</a>
		<div class='wp-submenu'><div class='wp-submenu-head'></div>
			<ul>
				<li class="wp-last-item"><a href='/backend/bitacora' tabindex="1">Búsquedas</a></li>
			</ul>
		</div>
	</li>

	<li class="wp-menu-separator"><a class="separator" href="#"><br /></a></li>
	
	<li class="wp-has-submenu menu-top menu-icon-tools  menu-top-first" id="menu-tools">
		<div class='wp-menu-image'><a href='#'><br /></a></div><div class="wp-menu-toggle"><br /></div><a href='' class="wp-has-submenu menu-top menu-icon-tools" tabindex="1">Herramientas</a>
		<div class='wp-submenu'>
			<ul>
				<li class="wp-last-item"><a href='/backend/export' tabindex="1">Exportar DB</a></li>
			</ul>
		</div>
	</li>

	<li class="wp-menu-separator-last"><a class="separator" href="#"><br /></a></li>

</ul>
