<div class="block-large" style="background-color: #E3E3E3;">
	<h2>Crear checkin especial para mi local</h2>
	<div>
		<p style="float:none;">

	<b> Que es un checkin especial ?</b> <br />
	Un checkin especial es una herramienta que ofrece Kuesty a los dueños de locales para atraer nuevos clientes a su local, ofreciendo un descuento o promocion definida por los mismos cada vez que un usuario realiza un checkin calificando el mismo. <br /> <br />
	
	<b> Como se entera un usuario de un checkin especial ? </b><br />
	Cuando el due&ntilde;o de un local crea un checkin especial, el mismo se ve reflajado en varios ambitos(movil, web, twitter, facebook, email) para poder comunicar a los usuarios de Kuesty de una nueva promoci&oacute;n en su lugar favorito o para atraer a nuevos usuarios a su local. Si un usuario es FAN de su local en Kuesty, entonces le llegara una notificacion a su telefono movil comunicando de su nueva promocion o descuento.<br /><br />

	<b> Cuando creo un checkin espcial instantaneamente se ve reflejado en la aplicacion ?</b><br />
	No, un checkin especial puede tardar en publicarse entre minutos y una hora como maximo ya que es previamente analizado por un moderador de Kuesty para verificarla congruencia del mismo, analizando que este redactado correctamente correctamente.<br /><br />

	<b> Como creo un checkin especial ? </b><br />
	Solo complete el siguientes formulario, y listo. A esperar que los usuarios de Kuesty lleguen en manada a su local para disfrutar del mismo.<br /><br />

	<b> Cual es el costo de generar un checkin especial ? </b><br />
	Generar un checkin especial para su local tiene un costo minimo. Una vez que crea un nuevo checkin especial para su local, se obtienen 7es una herramienta gratuita para todos los dueños de los locales.<br/><br/>
<br />

</p>

	<p style="color:red; font-size:18px; margin-bottom:10px;">Disponibles a partir del 25 de Julio de 2013 para Android</p>

	</div>

	<?php if(isset($this->checkin_created)) { ?>
		
	<form class="form-checkinspecial" method="POST">
	<div style="color:green">Felicitaciones! Has creado un nuevo checkin espcial, en unas horas estara activo para que tus clientes lo disfruten.</div>

	<div class="checkin-special">
		<p style="width:auto;">Todos los <span>
		<?php $dias = array("dias","lunes","martes", "miercoles", "jueves", "viernes", "sabados", "domingos"); echo $dias[$this->checkin["dia"]]; ?> </span> <span> <?php if($this->checkin["sin_horario"] == 0) { echo $this->checkin["hora_ini"]; ?> a <?php echo $this->checkin["hora_fin"]; } ?></span> haciendo checkin en <?php echo $this->local["nombre"];?> <span> <?php echo $this->checkin["descripcion"]; ?></span></p>
		<p style="font-size:11px;padding-top:5px;">Valido del <span> <?php echo $this->checkin["fecha_ini"]; ?></span> al <span> <?php echo $this->checkin["hora_fin"]; ?></span></p>
	</div>
	<input type="button" class="lindo-boton" value="Volver al perfil del local" style="float:none;" onclick="document.location.href='/restaurants/local/id/<?php echo $this->local["id"]; ?>'" />

	</form>
	<?php }else{ ?>

	<?php if(isset($this->ocheckin)) { ?>
	<form class="form-checkinspecial" method="POST">
	<div style="color:green;">IMPORTANTE! Ya tienes un checkin espcial creado para este local, por el momento solo se puede tener un checkin especial activo en Kuesty, por lo cual al ingresar los datos en el formulario de creacion de el checkin especial, el actual dejara de tener validez. Para mas informacion, comunicarse a <a href="mailto:info@kuesty.com" target="_blank" style="color:green; text-decoration:underline;">info@kuesty.com</a><br /><br />Este es tu checkin espcial actual: </div>
		<div class="checkin-special">
		<p style="width:auto;">Todos los <span>
		<?php $dias = array("dias","lunes","martes", "miercoles", "jueves", "viernes", "sabados", "domingos"); echo $dias[$this->ocheckin["dia"]]; ?> </span> <span> <?php if($this->ocheckin["sin_horario"] == 0) { echo $this->ocheckin["hora_ini"]; ?> a <?php echo $this->ocheckin["hora_fin"]; } ?></span> haciendo checkin en <?php echo $this->local["nombre"];?> <span> <?php echo $this->ocheckin["descripcion"]; ?></span></p>
		<p style="font-size:11px;padding-top:5px;">Valido del <span> <?php echo $this->ocheckin["fecha_ini"]; ?></span> al <span> <?php echo $this->ocheckin["hora_fin"]; ?></span></p>
	</div>
	<div style="color:green;">El checkin actual esta en estado: <?php $e = array("A"=>"Activo","P"=>"Pendiente","D"=>"Rechazado"); echo $e[$this->ocheckin["estado"]];?></div>	
	</form>
	<?php } ?>

	<div style="clear:both;">
		<p style="float:none;padding-top:0px;"><b>Formulario de creacion de checkin especial para <?php echo $this->local["nombre"]; ?></b></p>
	</div>

	<form class="form-checkinspecial" id="form-checkinspecial" method="POST">
	
	<div style="clear:both;"></div>
	<?php if($this->error) { ?>
	<div class="error">
		<?php echo implode($this->error, "<br />"); ?>
	</div>
	<?php } ?>
	<div class="form-checkin">
		Todos los 
		<select name="dia" id="dia">
			<!--option value="0">dias</option-->
			<option value="1">lunes</option>
			<option value="2">martes</option>
			<option value="3">miercoles</option>
			<option value="4">jueves</option>
			<option value="5">viernes</option>
			<option value="6">sabados</option>
			<option value="7">domingos</option>
		</select>

		<?php if($this->checkin) { ?>
		<script type="text/javascript">
			$('#dia option[value="<?php echo isset($this->checkin["dia"]) ? $this->checkin["dia"] : 0;?>"]').attr("selected","selected");
		</script>
		<?php } ?>
		<br />
		de <input type="text" name="hora_ini" id="hora_ini" value="<?php echo $this->checkin["hora_ini"];?>" /> a <input type="text" name="hora_fin" id="hora_fin" value="<?php echo $this->checkin["hora_fin"];?>" /> <input type="checkbox" id="sin_hora" name="sin_hora" <?php if($this->checkin["sin_horario"]) { echo 'checked="checked"'; } ?> /> Sin horario
		<br />
		en <b><?php echo $this->local["nombre"]; ?> </b> <br />
		<textarea id="descripcion" name="descripcion"><?php echo $this->checkin["descripcion"];?></textarea>
		<br />
		valido del <input type="text" name="fecha_ini" id="fecha_ini" value="<?php echo $this->checkin["fecha_ini"];?>" /> a <input type="text" name="fecha_fin" id="fecha_fin" value="<?php echo $this->checkin["fecha_fin"];?>" /> 
	</div>
	<br />
	<input type="button" onclick="kuesty.generateCheckinPreview()" class="lindo-boton" value="Generar vista previa" />
	<div style="clear:both;"></div>
	<div class="checkin-special">
		<p style="width:auto;">Todos los <span id="preview_dia"> </span> <span id="preview_hora"></span> haciendo checkin en 
		<?php echo $this->local["nombre"];?> <span id="preview_desc"></span></p>
		<p style="font-size:11px;padding-top:5px;">Valido del <span id="preview_fecha_ini"></span> al <span id="preview_fecha_fin"></span></p>
	</div>	
	<div style="clear:both;"></div>
	<p>Terminos y condiciones</p>
	<textarea  class="terms" disabled="disabled">
	Kuesty &reg; ayudara a los due&ntilde;os de los locales comerciales a promover sus promociones a trav&eacute;s del “checkin especial”, realizando pautas publicitarias en los distintos medios webs, entendi&eacute;ndose por tales la aplicaci&oacute;n m&oacute;vil de Kuesty, el sitio web de Kuesty y en las distintas redes sociales.

Los locales comerciales que generen “checkin especiales” asumen los costos que las ofertas publicadas a trav&eacute;s de dichos “checkin especial” pudieran ocasionarles, como as&iacute; tambi&eacute;n asumen la exclusiva responsabilidad respecto al contenido y alcances de las ofertas publicadas por medio de los “checkin especial”, liberando expresamente a Kuesty &reg; de todo tipo responsabilidad respecto de los costos que las ofertas pudieran representarles como as&iacute; tambi&eacute;n de los contenidos y alcances de las ofertas siendo los locales oferentes los &uacute;nicos y exclusivos responsables respecto de las ofertas publicadas por medio de los “checkin especiales”.

Al aceptar los presentes t&eacute;rminos y condiciones el local libera expresamente a Kuesty &reg; de cualquier reclamo futuro que pueda derivar de la publicidades y ofertas realizadas por los locales.</textarea>
	<div style="clear:both;"></div>
	<br />
	<label>Acepto los terminos y condiciones</label>
	<input type="checkbox" name="terminos" id="terminos" />
	<div style="clear:both;"></div>
	<input type="submit" class="lindo-boton" value="Crear Checkin Especial" />
	<input type="button" class="lindo-boton" value="Volver al perfil de local" onclick="document.location.href='/restaurants/local/id/<?php echo $this->local['id'];?>'" />
	<br /><br />
	<script type="text/javascript">
	$(function() {

		$("#fecha_ini, #fecha_fin").datepicker({dateFormat: 'dd-mm-yy'});
		$("#hora_ini, #hora_fin").timepicker();
    });

		function asktoleave() {
			return "Desea salir del formulario creacion del checkin especial ?";
		}
		window.onbeforeunload = asktoleave;

	kuesty.generateCheckinPreview();
	</script>
	</form>

	<?php } ?>
</div>
