<script> $('.fancybox').fancybox(); </script>

	<div class="block-large">
		<?php $local = $this->local; ?>
		<h2><?php echo($local["nombre"]);?> fans <span></span></h2>
	<div id="restoId" style="display:none"><?php echo($local["id"]) ?></div>
	<div class="user-profile">
		<a href="/restaurants/local/id/<?php echo $local["id"];?>"><img class="avatar" src="<?php if($local["logo"] == ""){ echo("http://www.kuesty.com/resources/images/no_image.png"); }else{ echo( $local["logo"]); }; ?>" alt="<?php echo($local["nombre"]);?>" width="150px;"/></a>
        
        	<div class="float-star">
                 <span class="stars">
					<?php for($j=1; $j <= $local["stars"]; $j++) { ?>
            		<a class="active" href=""></a>
					<?php } ?>	
					<?php for($j=0; $j < (5 -$local["stars"]); $j++) { ?>
            		<a href=""></a>
					<?php } ?>
            	</span>
            </div>
                
            <div class="float-star">
                <span class="dolar">
            		<?php for($j=1; $j <= $local["pesos"]; $j++) { ?>
            		<a class="active" href=""></a>
					<?php } ?>	
					<?php for($j=0; $j < (5 -$local["pesos"]); $j++) { ?>
            		<a href=""></a>
					<?php } ?>
            	</span>
            </div>
            
            <div class="map-road">
            	<img src="http://maps.google.com/maps/api/staticmap?center=<?php echo($local["latitud"]);?>,<?php echo($local["longitud"]);?>&size=268x143&mobile=true&format=png&sensor=false&zoom=15&markers=icon:http://kuesty.com/resources/images/map_pin.png|<?php echo($local["latitud"]);?>,<?php echo($local["longitud"]);?>" />

                <div class="clearer"></div>

				<a href="#mapa-grande" class="fancybox zoom-icon"></a>  			 
			</div>
			
            <div id="mapa-grande" style="display: none;">
				<p>
					<img src="http://maps.google.com/maps/api/staticmap?center=<?php echo($local["latitud"]);?>,<?php echo($local["longitud"]);?>&size=450x343&mobile=true&format=png&sensor=false&zoom=15&markers=icon:http://kuesty.com/resources/images/map_pin.png|<?php echo($local["latitud"]);?>,<?php echo($local["longitud"]);?>" />
				</p>
			</div>

            
        <div class="links-user profile">
            <div class="line-break"></div>
			<a class='friends' style="padding:10px 0px 0px 15px;"><span></span><?php echo((int)$local["cant_fans"]);?> fans</a>
			<a class='tips' style="padding-top:10px;"><span></span><?php echo((int)$local["cantidad_tips"]); ?> tips</a>
			<a class='checkin' style="padding-left:15px;"><span> </span><?php echo( (int)$local["cantidad_checkins"]); ?> check-ins</a>
			<a class='review2'><span> </span><?php echo((int)$local["cantidad_reviews"]); ?> rese&ntilde;as</a>
		</div>
        
        <!-- a class="fan-icon" href="">Hazte fan</a -->                
    
    </div>


	<div class="address">
		<span><?php echo($local["direccion"]); ?></span>
		Tel: <?php echo($local["telefono"]); ?>
	</div>
	<div>
		<?php if($local["facebook"] != "") { ?> 
		<div><a target="_blank" href="<?php echo($local["facebook"]); ?>"><img src="/resources/images/facebook.png" style="margin-left:18px;margin-top:5px;" width="15px" /></a></div>
		<?php } ?>
		
		<?php if($local["twitter"] != "") { ?> 
		<div><a target="_blank" href="<?php echo($local["twitter"]); ?>"><img src="/resources/images/twitter.png" style="margin-left:18px;margin-top:5px;" width="15px" /></a></div>
		<?php } ?>

	</div>
		 <div class="icons-food">
			<?php 
			$categorias = $local["categorias"];
			foreach($categorias as $categoria) { ?>
				<a class="<?php echo($categoria["cssClass"]); ?>" href="/restaurants/?q=&cat=<?php echo($categoria["id"]);?>" title="<?php echo($categoria["nombre"]);?>"><img src="<?php echo($categoria["imgURL"]);?>" width="36px" height="36px" alt="<?php echo($categoria["nombre"]);?>" /></a>
			<?php } ?>
		</div>

	<div class="clearer"></div>

	<div class="status">
		<textarea id="localStatus" disabled="disabled"><?php if($this->status && trim($this->status["post"]) != "") { echo "&ldquo;".$this->status["post"]."&rdquo;"; } ?></textarea>
	</div>


	<div class="clearer"></div>

	 <div class='modal friendslist'>
    	<h3>Fans<span></span></h3>
		 
		
           <?php foreach($this->fans as $k=>$friend){ ?>
		    <div class="friendlist_friend">
			<a href='/user/id/<?php echo $friend["id"];?>/user/<?php echo $friend["user"];?>'>
                    <img width="50px" src='/user/avatar/id/<?php echo $friend["id"]?>' />
				</a>
				<p><b><?php echo $friend["user"];?></b><br />
				<?php echo $friend["puntos"]; ?> puntos<br />
				<a class="friends"> <span></span> <?php echo $friend["cantidad_amigos"]; ?> amigos</a></p>
			</div>	
			<?php } ?>

    </div>
    </div>

	

<div class="top-users">
    <h2>Destacados</h2>
    	
		<?php foreach($this->tops as $local) {  ?>
    	<div class="user local-fan-costado" onclick="document.location.href = '/restaurants/local/id/<?php echo($local['id']);?>/name/<?php echo(preg_replace("/\s+/","-",$local['nombre']));?>'">
    		<img src="<?php echo( $local["logo_mobile"]);?>" alt="<?php echo(preg_replace("/\s+/", "-", $local["nombre"])); ?>" style="width:50px;min-height:50px;"/>
    		<p><?php echo($local["nombre"]);?>
			<div class="rank-dolar duplicate">
				<span class="stars">
              		<?php for($j=1; $j <= $local["stars"]; $j++) { ?>
            		<a class="active" href=""></a>
					<?php } ?>	
					<?php for($j=0; $j < (5 -$local["stars"]); $j++) { ?>
            		<a href=""></a>
					<?php } ?>

				 </span>
                <span class="dolar">
  					<?php for($j=1; $j <= $local["pesos"]; $j++) { ?>
            		<a class="active" href=""></a>
					<?php } ?>	
					<?php for($j=0; $j < (5 -$local["pesos"]); $j++) { ?>
            		<a href=""></a>
					<?php } ?>
				</span>
			</div>
			</p>
    		<div class="clearer"></div>
    	</div>
    	<?php } ?>
    	
    </div>


