	<script> $('.fancybox').fancybox(); </script>

	<div class="block-large hreview-aggregate">
		<?php $local = $this->local; ?>
		<h2><?php echo($local["nombre"]);?><span> </span></h2>
	<div id="restoId" style="display:none"><?php echo($local["id"]) ?></div>
	<div class="user-profile item">
	<a href="<?php echo $local["logo"]; ?>" class="fancybox">
		<img class="avatar" src="<?php if($local["logo"] == ""){ echo("http://www.kuesty.com/resources/images/no_image.png"); }else{ echo( $local["logo"]); }; ?>" alt="<?php echo($local["nombre"]);?>" width="150px;"/>
</a>
        
        	<div class="float-star">
                 <span class="stars">
					<?php for($j=1; $j <= $local["stars"]; $j++) { ?>
            		<a class="active" href=""></a>
					<?php } ?>	
					<?php for($j=0; $j < (5 -$local["stars"]); $j++) { ?>
            		<a href=""></a>
					<?php } ?>
            	</span>
            </div>
            <div class="float-star">
                <span class="dolar">
            		<?php for($j=1; $j <= $local["pesos"]; $j++) { ?>
            		<a class="active" href=""></a>
					<?php } ?>	
					<?php for($j=0; $j < (5 -$local["pesos"]); $j++) { ?>
            		<a href=""></a>
					<?php } ?>
            	</span>
            </div>
           
			<div style="display:none;"> 
				<div class="rating"><?php echo $local["stars"]; ?></div>
				<div class="price"><?php echo $local["pesos"]; ?></div>
				<div class="count"><?php echo  ((int)$local["cantidad_checkins"] + (int) $local["cantidad_reviews"]); ?></div>
			</div>

            <div class="map-road">
            	<img src="http://maps.google.com/maps/api/staticmap?center=<?php echo($local["latitud"]);?>,<?php echo($local["longitud"]);?>&size=268x143&mobile=true&format=png&sensor=false&zoom=15&markers=icon:http://kuesty.com/resources/images/map_pin.png|<?php echo($local["latitud"]);?>,<?php echo($local["longitud"]);?>" />

                <div class="clearer"></div>

				<a href="#mapa-grande" class="fancybox zoom-icon"></a>  			 
			</div>
			
            <div id="mapa-grande" style="display: none;">
				<p>
					<img src="http://maps.google.com/maps/api/staticmap?center=<?php echo($local["latitud"]);?>,<?php echo($local["longitud"]);?>&size=450x343&mobile=true&format=png&sensor=false&zoom=15&markers=icon:http://kuesty.com/resources/images/map_pin.png|<?php echo($local["latitud"]);?>,<?php echo($local["longitud"]);?>" />
				</p>
			</div>

            
        <div class="links-user profile">
            <div class="line-break"></div>
			<a class='friends' style="padding:10px 0px 0px 15px;"><span></span><?php echo((int)$local["cant_fans"]);?> fans</a>
			<a class='tips' style="padding-top:10px;"><span></span><?php echo((int)$local["cantidad_tips"]); ?> tips</a>
			<a class='checkin' style="padding-left:15px;"><span> </span><?php echo( (int)$local["cantidad_checkins"]); ?> check-ins</a>
			<a class='review2'><span> </span><?php echo((int)$local["cantidad_reviews"]); ?> rese&ntilde;as</a>
		</div>

			 <div class="icons-food">
			<?php 
			$categorias = $local["categorias"];
			foreach($categorias as $categoria) { ?>
				<a class="<?php echo($categoria["cssClass"]); ?>" href="/restaurants/?q=&cat=<?php echo($categoria["id"]);?>" title="<?php echo($categoria["nombre"]);?>"><img src="<?php echo($categoria["imgURL"]);?>" width="36px" height="36px" alt="<?php echo($categoria["nombre"]);?>" /></a>
			<?php } ?>
		</div>
	
        <!-- a class="fan-icon" href="">Hazte fan</a -->                
    
	</div>

	<?php if($this->local["cerrado_temporalmente"]) { ?>
	<div class="horario_open">
		<img src="/resources/images/_close.png" /><a>Cerrado temporalmente</a>
	</div>
	<?php }elseif($this->horarios) { ?>
	<div class="horario_open">

		<?php if($this->open) { ?>
			<img src="/resources/images/_open.png" /><a>Abierto</a>
		<?php } else { ?>
			<img src="/resources/images/_close.png" /><a>Cerrado</a>
		<?php } ?>
	</div>
	<?php } ?>

	<div style="clear:both;"></div>


	<?php if($this->session_user["id"]) { ?>
	<div id="dialog-modal" style="display:none;">
		<iframe src="/restaurants/activate/id/<?php echo $local["id"];?>" width="100%" height="100%" frameborder="none"></iframe>
	</div>
	<?php } ?>

	<?php $propietario = $this->session_user["id"] == (int)$local["id_user_propietario"] || 
						$this->session_user["id"] == 1 ||
						$this->session_user["id"] == 12 ?>

	<?php if($this->session_user["id"] && $propietario) { ?>
		<div style="float:right; margin-right:10px;" class="lindo-boton">
			<a style="color:white;" href="/restaurants/edit/id/<?php echo($local['id']); ?>">Modificar datos</a>
		</div>

		<div id="cespecialBtt" style="float:right;" class="lindo-boton">
			<a style="color:white;" href="/restaurants/addcheckin/id/<?php echo($local['id']); ?>">Crear checkin especial</a>
		</div>
		<?php if(!$this->cespecial) { ?>

			<script type="text/javascript">

				guiders.createGuider({
			      attachTo: "#cespecialBtt",
					  buttons: [{name: "Cerrar", onclick : guiders.hideAll }, {name: "Crear checkin especial", onclick: function(){ document.location.href='/restaurants/addcheckin/id/<?php echo $this->local['id'];?>'}}],

				  description: "Si, quiero atraer nuevos clientes a <?php echo $this->local["nombre"];?>! Bueno, entonces deberias crear un checkin especial para atraer a los usuarios de Kuesty. Crea promos y descuentos para tus clientes de una manera facil.",
			      id: "second",
			      position: 1,
				  title: "Queres nuevos clientes en <?php echo $this->local["nombre"];?>?"
			    }).show();

				setTimeout("guiders.hideAll()", 15000);
				$("#second").find("p").css("text-align", "left");
			</script> 


		<?php } ?> 

	<?php } ?>
	
	<?php if($this->session_user["id"] && $propietario) { ?>
		<div id="reclamarLocalBtt" style="float:right; margin-right:10px;">
			<button onclick="kuesty.enableStatusEdit(<?php echo($local['id']); ?>, this)" class="lindo-boton">Actualizar estado</button>
		</div>
	<?php } ?>



	<?php if( !$propietario && $this->session_user["id"]) { ?>
		<div id="reclamarLocalBtt" style="">
			<!-- button onclick="kuesty.claim(<?php echo $local['id'] ?>)" class="lindo-boton">Reclamar local</button-->
			<button onclick="kuesty.claim(<?php echo $local['id'] ?>)" class="lindo-boton">Reclamar local</button>
		</div>
		<div style="clear:both;"></div>
	<?php } ?>

	<?php if($this->session_user["id"]) { ?>
	<div style="float:none;"><button id="addfanbtt" onclick="kuesty.addFan(<?php echo($local['id']); ?>)" class="lindo-boton">
			<?php if($this->userisfan) { echo "Dejar de ser fan"; } else { echo "Hazte fan"; } ?>
	</button></div>
	<?php } ?>


	<div style="clear:both;"></div>
	<br />
	<div class="address">
		<span><?php echo($local["direccion"]); ?></span>
		Tel: <?php echo($local["telefono"]); ?>
	</div>

	<div class="clearer"></div>

	<div class="resto_social">
		<?php if($local["facebook"] != "") { ?> 
		<div><a target="_blank" href="<?php echo($local["facebook"]); ?>"><img src="/resources/images/facebook.png" style="margin-left:18px;margin-top:5px;" width="15px"  /><?php $local["facebook"];?></a></div>
		<?php } ?>
		
		<?php if($local["twitter"] != "") { ?> 
		<div><a target="_blank" href="http://twitter.com/<?php echo($local["twitter"]); ?>"><img src="/resources/images/twitter.png" style="margin-left:3px;margin-top:5px;" width="15px"  /><?php $local["twitter"]; ?></a></div>
		<?php } ?>

	</div>

	<?php if($this->especial){ ?>
	<div class="checkin-special">
		<p><?php echo($this->especial["descripcion"]); ?></p>
	</div>
	<?php } ?>
	<div class="status">
		<p style="<?php if($this->status["post"]==""){ echo "display:none;"; } ?>"><?php echo $this->status["post"]; ?></p>
		<textarea id="localStatus" style="display:none;" disabled="disabled"><?php if($this->status && trim($this->status["post"]) != "") { echo "&ldquo;".$this->status["post"]."&rdquo;"; } ?></textarea>
	</div>

		<?php if($this->cespecial) { ?>
		<div id="resto_cespecial" class="resto_promo status">
		<?php $dias = array(
			"1"=>"lunes", 
			"2"=>"martes", 
			"3"=>"miercoles", 
			"4"=>"jueves", 
			"5"=>"viernes", 
			"6"=>"sabados", 
			"7"=>"domingos" 
		); ?>
			<p style="width:auto; float:none;">Todos los <?php echo $dias[$this->cespecial["dia"]];?> <?php if(!$this->cespecial["sin_horario"]) { echo $this->cespecial["hora_ini"]?> a <?php echo $this->cespecial["hora_fin"]; } ?> haciendo checkin en <?php echo $this->local["nombre"];?> <?php echo $this->cespecial["descripcion"];?><br />
		</p>
	<span style="font-size:11px;padding-top:5px; float:right; text-align:right;">
		<?php $times_unlocked = $this->cespecial["times_unlocked"]; ?>
		<?php if($times_unlocked > 0) { ?>
			<!-- strong>Esta promoci&oacute;n se ha usado <?php echo $times_unlocked ?>  
			<?php echo $times_unlocked > 1 ? "veces" : "vez" ?></strong> | --> 
		<?php } ?>
	Valido del <?php echo $this->cespecial["fecha_ini"];?> al <?php echo $this->cespecial["fecha_fin"];?></span>
		</div>
	<script type="text/javascript">

	guiders.createGuider({
      attachTo: "#resto_cespecial",
	  buttons: [{name: "Cerrar", onclick : guiders.hideAll }],

      description: "Ahora puedes encontrar descuentos y promociones en distintos locales de la ciudad! Es muy facil, solo tienes que hacer checkin cuando estes en un local con promocion, muestraselo a la moza, y lesto! (lesto tiene mas onda que listo)",
      id: "second",
      position: 11,
	  title: "Que bien! Una promocion en <?php echo $this->local["nombre"];?>!"
    }).show();

	setTimeout("guiders.hideAll()", 15000);
	$("#second").find("p").css("text-align", "left");
	</script> 

	<?php } ?>	

    <div class="review-content">
    
    	<div class="title">escribir rese&ntilde;a</div>
        
        <div class="califica">
        	Califica este lugar
            
           <div class="rank-dolar duplicate2">

				 <span id="calificacionEstrellas" class="stars">
					<a onclick="kuesty.llenoEstrellas(1,$(this))" 
						onmouseover="kuesty.overEstrellas(1,$(this))" 
						onmouseout="kuesty.outEstrellas($(this))"></a>
					<a onclick="kuesty.llenoEstrellas(2,$(this))" 
						onmouseover="kuesty.overEstrellas(2,$(this))"
						onmouseout="kuesty.outEstrellas($(this))"></a>
					<a onclick="kuesty.llenoEstrellas(3,$(this))" 
						onmouseover="kuesty.overEstrellas(3,$(this))"
						onmouseout="kuesty.outEstrellas($(this))"></a>
					<a onclick="kuesty.llenoEstrellas(4,$(this))" 
						onmouseover="kuesty.overEstrellas(4,$(this))"
						onmouseout="kuesty.outEstrellas($(this))"></a>
					<a onclick="kuesty.llenoEstrellas(5,$(this))" 
						onmouseover="kuesty.overEstrellas(5,$(this))"
						onmouseout="kuesty.outEstrellas($(this))"></a>
				</span>
				<input type="hidden" id="aux_estrellas" value="0" />
				<input type="hidden" id="aux_pesos" value="0" />

				<span id="calificacionPesos" class="dolar">
					<a onclick="kuesty.llenoEstrellas(1,$(this), true)" 
						onmouseover="kuesty.overEstrellas(1,$(this))" 
						onmouseout="kuesty.outEstrellas($(this), true)"></a>

					<a onclick="kuesty.llenoEstrellas(2,$(this), true)" 
						onmouseover="kuesty.overEstrellas(2,$(this))"
						onmouseout="kuesty.outEstrellas($(this), true)"></a>

					<a onclick="kuesty.llenoEstrellas(3,$(this), true)" 
						onmouseover="kuesty.overEstrellas(3,$(this))"
						onmouseout="kuesty.outEstrellas($(this), true)"></a>

					<a onclick="kuesty.llenoEstrellas(4,$(this), true)" 
						onmouseover="kuesty.overEstrellas(4,$(this))"
						onmouseout="kuesty.outEstrellas($(this), true)"></a>

					<a onclick="kuesty.llenoEstrellas(5,$(this), true)" 
						onmouseover="kuesty.overEstrellas(5,$(this))"
						onmouseout="kuesty.outEstrellas($(this), true)"></a>
               	</span>
               	
			         	</div>

        </div>
        
      <div class="review-form">
        	
          <form> 
          	<label>Escribe una rese&ntilde;a</label>
			<textarea id="contenidoReview" name=""></textarea><br />
			<div> 
				<input type="checkbox" id="shareFB" /> <label style="display: inline-block;
font-size: 12px;
color: #000;
margin-top: 10px;
clear: left;" for="shareFB"> Compartir mi reseña en Facebook</label>
			</div>

          	<input type="button" onclick="kuesty.enviarResena()" value="aceptar"/>
          	<input name="Reset" type="reset" value="cancelar"/>
          </form>
            
        
        </div>
    
    </div>
    
    <div class="clearer"></div>
   <div class="line-break medium"></div>


	<div class="review">    
    
    	<p style="padding-bottom:15px;width:540px;"><?php echo($local["descripcion"]); ?></p>
		<p><b>Horarios:</b></p>
		<?php 
			$len = sizeof($this->horarios);

			foreach($this->horarios as $i => $horario) { 
			
			$dia = $horario["dia"];
			switch($dia) {
				case 0: $dia = "Lun. "; break;
				case 1: $dia = "Mar. "; break;
				case 2: $dia = "Mie. "; break;
				case 3: $dia = "Jue. "; break;
				case 4: $dia = "Vie. "; break;
				case 5: $dia = "Sab. "; break;
				case 6: $dia = "Dom. "; break;
				case 7: $dia = "Fer. "; break;
			};	
			?><p <?php if($i==($len-1)) { ?> style="padding-bottom:10px;" <?php } ?>><?php 

			echo $dia." ".$horario["hora_ini"]." - ".$horario["hora_fin"];	?></p>
		<?php } ?>

		<?php foreach($this->extras as $extra) { ?>
		<p style="width:150px;"><b><?php echo $extra["nombre"]; ?>: </b>
<?php 
			if($extra["yesno"] == 1) echo "Si";
			else echo "-"; 
			if($extra["opcional"]) echo $extra["opcional"]; ?>
		</p>
		<?php } ?>

    </div>


    <?php if($this->session_user["id"]) { ?>
        <a class="make-review" href="">escribir rese&Ntilde;a</a>
    <?php } ?>
 
    <div class="clearer"></div>
 
	<div class="fb-like-local">
		<?php if($this->local["facebook"]) {
			// $this->facebookURL = $this->local["facebook"];
		} ?>
		<iframe src="//www.facebook.com/plugins/like.php?href=<?php echo(urlencode($this->facebookURL));?>/?&amp;send=false&amp;layout=button_count&amp;width=450&amp;show_faces=false&amp;action=like&amp;colorscheme=light&amp;font&amp;height=35&amp;appId=150317021676268" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:450px; height:35px;" allowTransparency="true"></iframe>
	</div>

    
    <!--div class="clearer"></div-->
    
	<div class="clearer"></div>

	 <!-- div class="modal">
		<h3  style="margin-bottom:8px;">Algunas fotos<span></span></h3>
			
			<form id="imageform" method="post" enctype="multipart/form-data" action="/ajax/uploadprofileimage" style="display:none;">
				<div id="change-img" onmouseover="" onmouseout="" style="overflow: hidden; cursor: pointer; background-color: orange; opacity: 0.8; text-align: center; width: 100px; height: 23px; position: absolute; display: none;">Cambiar<input style="position: relative;top: -10px;left: -15px;height: 23px;width: auto;opacity: 0;" type="file" name="photoimg" id="photoimg"></div>
			</form>

			<div class="localImageChanger">
				<img src="http://www.kuesty.com/resources/locales/746/thumb_746_o.png" width="18%" height="auto" />
			</div>
			<div class="localImageChanger">
				<img src="http://www.kuesty.com/resources/locales/746/thumb_746_o.png" width="18%" height="auto" />
			</div>

			<div class="localImageChanger">
				<img src="http://www.kuesty.com/resources/locales/746/thumb_746_o.png" width="18%" height="auto" />
			</div>
			
			<div class="localImageChanger">
				<img src="http://www.kuesty.com/resources/locales/746/thumb_746_o.png" width="18%" height="auto" />
			</div>

			<div class="localImageChanger">
				<img src="http://www.kuesty.com/resources/locales/746/thumb_746_o.png" width="18%" height="auto" />
			</div>

		</div -->
    



	 <div class='modal friendslist'>
    	<h3>Fans<span></span></h3>
		 
			<?php if(sizeof($this->fans)) { ?>
           <?php foreach($this->fans as $k=>$friend){ ?>
		    <div class="friendlist_friend">
			<a href='/user/id/<?php echo $friend["id"];?>/user/<?php echo $friend["user"];?>'>
                    <img width="50px" src='/user/avatar/id/<?php echo $friend["id"]?>' />
				</a>
				<p><b><?php echo $friend["user"];?></b><br />
				<?php echo $friend["puntos"]; ?> puntos<br />
				<a class="friends"> <span></span> <?php echo $friend["cantidad_amigos"]; ?> amigos</a></p>
			</div>	
			<?php } ?>
			<?php if(sizeof($this->fans) >= 3) { ?>
				<a href="/restaurants/fans/id/<?php echo $this->local["id"]; ?>" class="vermasBtt"></a>
			<?php } ?>
			<?php }else{ ?>
			<span class='empty-data'><?php echo $this->local["nombre"];?> no tiene fans todav&iacute;a. <br /> Hacete fan de <?php echo $this->local["nombre"];?> y enterate de sus promos y descuentos al instante.</span>
			<?php } ?>


    </div>

    <div class='modal'>

		<?php if($this->rid) { $review = $this->review; ?>
		<div id="resenia-seleccionada">
		<h6 id="rid<?php echo $this->rid; ?>">Rese&ntilde;a<?php $review["user"]; ?><span></span></h6>

			<div class="tit-tips"><?php echo($review["titulo"]); ?> 
				<span> 
					<a href="/user/?id=<?php echo($review["id_user"]);?>&user=<?php echo($review["user"]);?>" style="float:left;">
						<img class="user-en-review" src="/user/avatar/id/<?php echo $review["id_user"] ?>" alt="<?php echo($review["user"]);?>" height="50" width="50" />
					</a>
					<div style="float:left;padding-left:5px;">
						<a style="font-size:12px;padding-bottom:3px;" href="/user/?id=<?php echo($review["id_user"]);?>&user=<?php echo($review["user"]);?>"> <?php echo($review["user"]); ?>
						</a> 
						<div style="padding-bottom:3px;"><?php echo(date("d/m/Y", strtotime($review["fecha"] .'+ 4 hours'))); ?></div>
					</div>
				</span>
			</div>
            
            <div class="rank-dolar duplicate">
                <span class="stars">
				<?php for($j=1; $j <= $review["rating"]; $j++) { ?>
           		<a class="active" href=""></a>
				<?php } ?>	
				<?php for($j=0; $j < (5 -$review["rating"]); $j++) { ?>
           		<a href=""></a>
				<?php } ?>
            	</span>
                <span class="dolar">
            		<?php for($j=1; $j <= $review["price"]; $j++) { ?>
            		<a class="active" href=""></a>
					<?php } ?>	
					<?php for($j=0; $j < (5 -$review["price"]); $j++) { ?>
            		<a href=""></a>
					<?php } ?>
				</span>
                
         	</div>

            <div class="clearer separator"></div>
            
            <p style="white-space:pre-line;"><?php echo($review["comentario"]);?><br /><br /></p>
            
            <div class="clearer"></div>
            
            <div class="clearer"></div>


		<script type="text/javascript">
		$(document).ready(function(){
			$.scrollTo("#rid<?php echo $this->rid; ?>", 800);
		});
		</script>
		</div><!-- reseña seleccionada -->
		<?php } ?>

    	<h6>Ultimas rese&ntilde;as <span></span></h6>

		<?php if(count($this->reviews) == '0'){
				  echo("<span class='empty-data'>El local no tiene ninguna rese&ntilde;a todav&iacute;a</span>");
				}else{


				foreach($this->reviews as $review) { ?>
			<div id="review<?php echo $review["id"];?>">
			<div class="tit-tips"><?php echo($review["titulo"]); ?> 
				<span> 
					<a href="/user/?id=<?php echo($review["id_user"]);?>&user=<?php echo($review["user"]);?>" style="float:left;">
						<img class="user-en-review" src="/user/avatar/id/<?php echo $review["id_user"] ?>" alt="<?php echo($review["user"]);?>" height="50" width="50" />
					</a>
					<div style="float:left;padding-left:5px;">
						<a style="font-size:12px;padding-bottom:3px;" href="/user/?id=<?php echo($review["id_user"]);?>&user=<?php echo($review["user"]);?>"> <?php echo($review["user"]); ?>
						</a> 
						<div style="padding-bottom:3px;"><?php echo(date("d/m/Y", strtotime($review["fecha"] .'+ 4 hours'))); ?></div>
					</div>
				</span>
			<div class="rank-dolar duplicate">
				<span class="stars">
				<?php for($j=1; $j <= $review["rating"]; $j++) { ?>
				<a class="active" href=""></a>
				<?php } ?>	
				<?php for($j=0; $j < (5 -$review["rating"]); $j++) { ?>
				<a href=""></a>
				<?php } ?>
				</span>
				<span class="dolar">
					<?php for($j=1; $j <= $review["price"]; $j++) { ?>
					<a class="active" href=""></a>
					<?php } ?>	
					<?php for($j=0; $j < (5 -$review["price"]); $j++) { ?>
					<a href=""></a>
					<?php } ?>
				</span>

			</div>
			</div>
            
            <div class="clearer separator"></div>
            
            <p style="white-space:pre-line;"><?php echo($review["comentario"]);?><br /><br /></p>
            
            <div class="clearer"></div>
            
            <!-- div class="happy-face"><span></span>123</div-->
            <!-- div class="sad-face"><span></span>4</div-->
            
            <!-- a class="flag" href=""><span></span>Denunciar</a-->

			<div style="margin-top:5px; text-align:right;">	

				<!--iframe src="//www.facebook.com/plugins/like.php?href=http://kuesty.com/restaurants/local/id/<?php echo $this->local["id"];?>/rid/<?php echo $review["id"];?>&send=false&amp;layout=button_count&amp;width=450&amp;show_faces=false&amp;font&amp;colorscheme=light&amp;action=recommend&amp;height=21&amp;appId=106941089437708" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:120px; height:21px;" allowTransparency="true"></iframe-->

				<?php 
				if($this->local["twitter"] == "") {	
					$nombre_local = rawurlencode($this->local["nombre"]); 
				} else {
					$nombre_local = $this->local["twitter"];
				}
				?>
				<a href="https://twitter.com/intent/tweet?text=Les comparto la reseña de <?php echo $review["user"];?> sobre <?php echo $nombre_local;?>" class="twitter-share-button" data-related="kuestyapp" data-lang="es" data-size="medium" data-url="http://kuesty.com/restaurants/local/id/<?php echo $this->local["id"];?>/rid/<?php echo $review["id"];?>" data-dnt="true">Compartir</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
			
			</div>


            <div class="clearer review-top-bar"></div>

		</div>
			<?php }
			} ?>
    
    		<!-- button class="view-more">ver mas</button -->
    
	</div>
	<br />

    
    <div class='modal tips'>
    
    	<h4>Ultimos tips <span></span></h4>
		<?php $i = 0; ?>

		<?php if(count($this->tips) == '0'){
				  echo("<span class='empty-data'>El local no tiene calificaciones todav&iacute;a</span>");
				}else{
				foreach($this->tips as $tip) { ?>
			<div style="float:left; width:350px;">
			<div class="tit-tips">

				<img  width="75px" class='avatar' src='/user/avatar/id/<?php echo $tip["id_user"] ?>' alt="<?php echo($tip["user"]);?>" style="margin-right:15px; min-height:60px;"/>
				<a href="/user/id/<?php echo($tip["id_user"]);?>/user/<?php echo($tip["user"]);?>"><?php echo($tip["user"]); ?></a> <br /><span> <?php echo(date("d/m/Y", strtotime($tip["fecha"] .'+ 4 hours'))); ?></span></div>
            
            <div class="rank-dolar2 duplicate4">
                <span class="stars">
				<?php for($j=1; $j <= $tip["rating"]; $j++) { ?>
           		<a class="active" href=""></a>
				<?php } ?>	
				<?php for($j=0; $j < (5 -$tip["rating"]); $j++) { ?>
           		<a href=""></a>
				<?php } ?>
            	</span>
                <span class="dolar">
            		<?php for($j=1; $j <= $tip["price"]; $j++) { ?>
            		<a class="active" href=""></a>
					<?php } ?>	
					<?php for($j=0; $j < (5 -$tip["price"]); $j++) { ?>
            		<a href=""></a>
					<?php } ?>
				</span>
                
         	</div>
            
            <p style="width:260px;"><?php echo  $tip["tip"];?><br /><br /></p>
            
            <div class="clearer"></div>
            
            <!-- div class="happy-face"><span></span>123</div-->
            <!-- div class="sad-face"><span></span>4</div-->
            
            <!-- a class="flag" href=""><span></span>Denunciar</a-->
            
			</div>  
			<?php $i++; if( ($i%2) == 0) { echo '<div class="clearer"></div> <div class="clearer separator"></div>'; } ?>
             
			<?php }
				} ?>
       
    </div>
		
	</div>

<div class="top-users">
    <h2>Destacados</h2>
    	
		<?php foreach($this->tops as $local) {  ?>
    	<div class="user local-fan-costado" onclick="document.location.href = '/restaurants/local/id/<?php echo($local['id']);?>/name/<?php echo(preg_replace("/\s+/","-",$local['nombre']));?>'">
    		<img src="<?php echo( $local["logo_mobile"]);?>" alt="<?php echo(preg_replace("/\s+/", "-", $local["nombre"])); ?>" style="width:50px;min-height:50px;"/>
    		<p><?php echo($local["nombre"]);?>
			<div class="rank-dolar duplicate">
				<span class="stars">
              		<?php for($j=1; $j <= $local["stars"]; $j++) { ?>
            		<a class="active" href="/restaurants/local/id/<?php echo($local['id']);?>/name/<?php echo(preg_replace("/\s+/","-",$local['nombre']));?>"></a>
					<?php } ?>	
					<?php for($j=0; $j < (5 -$local["stars"]); $j++) { ?>
            		<a href="/restaurants/local/id/<?php echo($local['id']);?>/name/<?php echo(preg_replace("/\s+/","-",$local['nombre']));?>"></a>
					<?php } ?>

				 </span>
                <span class="dolar">
  					<?php for($j=1; $j <= $local["pesos"]; $j++) { ?>
            		<a class="active" href="/restaurants/local/id/<?php echo($local['id']);?>/name/<?php echo(preg_replace("/\s+/","-",$local['nombre']));?>"></a>
					<?php } ?>	
					<?php for($j=0; $j < (5 -$local["pesos"]); $j++) { ?>
            		<a href="/restaurants/local/id/<?php echo($local['id']);?>/name/<?php echo(preg_replace("/\s+/","-",$local['nombre']));?>"></a>
					<?php } ?>
				</span>
			</div>
			</p>
    		<div class="clearer"></div>
    	</div>
    	<?php } ?>
    	
    </div>

<script type="text/javascript">
		function checkReview() {
			if($("#contenidoReview").val() != "") {
				return "Desea descartar la reseña que estaba escribiendo ?";
			}
		}
		window.onbeforeunload = checkReview;
	</script>
