<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
	<title>Kuesty!</title>
	
	<link rel="stylesheet" href="/resources/css/jquery.mobile-1.0b3.min.css" />
	<link rel="stylesheet" href="/resources/css/style.css" />

	<script src="/resources/js/jquery-1.6.2.min.js"></script>
	<script src="/resources/js/jquery.mobile-1.0b3.min.js"></script>
	<script src="/resources/js/kuestyFront.js"></script>
	<style>
		.ui-page {
			background: #EEE;
		}
	</style>
    </head>
<body>
	<div style="text-align:center;width:100%;padding-top:20px;"><img src="resources/images/logo-mail.png" /></div>
	<?php if(!$this->isBB) { ?>
	<script type="text/javascript">
		try {
			navigator.geolocation.getCurrentPosition(function(geo) {
				_geo = geo;
				kuesty.getNearby(geo.coords.latitude, geo.coords.longitude, function(data) {
					if(data.locales.length) {
						try { 
							$("#nearbyList").html(data.html); 							 
							$("#nearbyList").find(" li > a ").each(function(){ 
								var ref = this.getAttribute("href");
									ref = 'window.open("http://kuesty.com'+ref+'")';
								this.setAttribute("href","#");
								this.setAttribute("onclick", ref);
							});
						}catch(e) {}				
					}else {
						$("#nearbytitle, #nearby_guider").hide();	
					}
				});
			});	
		}catch(e) { }		
	</script>
	<?php } ?>
	<h2 style="padding:20px;padding-bottom:0px;">Descarga Kuesty en tu celular! La primer guía móvil de bares y restos de Rosario. Mira los locales que tienes cerca, los destacados, comparte tu comentario de cada uno, gana puntos y canjealos por premios y descuentos!!!<br /><br /></h2>
	<?php if(!$this->isBB) { ?>
	<h2 id="nearbytitle">Locales cerca tuyo:</br></h2>
	<div id="nearby_guider" class="block" style="height: 262px; overflow: hidden; width: 100%;">
		<ul id="nearbyList"></ul>
		</div>
	<?php } ?>
	<h2><br />Elige tu celu</br></h2>
	<form id="our_login_form" style="padding-top:0px;" method="post" data-ajax="false">
    	<input type="button" value="iPhone" onclick="document.location.href = 'http://goo.gl/NUq8r'" data-theme="b" />
    	<input type="button" value="Android" onclick="document.location.href = 'http://goo.gl/C2t3D'" data-theme="b" />
    	<input type="button" value="Blackberry" onclick="document.location.href = 'http://goo.gl/UHF67'" data-theme="b" />
    	<input type="button" value="Blackberry OTA" onclick="document.location.href = 'http://goo.gl/sEkg3'" data-theme="b" />
	</form> <br>
</body>
</html>
