
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head>

	<title>
		Kuesty - Pagina no encontrada
	</title>

<!-- Meta Tags -->
<meta name="robots" content="noindex, nofollow" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<style>
	body{
		margin: 0 auto;
		text-align: center;
		/*font-family: Arial, Helvetica, sans-serif;*/
		font-size: 12px;
		color: #333;
		background-image: url(../../resources/img/bg-sddtandard3.png),url(../../resources/img/bg-pattern.png);
		background-repeat: repeat-x,repeat;
		background-position: center top,center bottom;
		margin: 17px 0 15px 0;
		font-family: "Lucida Grande","Lucida Sans Unicode", Tahoma, sans-serif;
		letter-spacing: .01em;
	}
	#container {
		background: #BC3C1F url(../../resources/images/bgerror.png) repeat-y;
		color: #FACD64;
		border: 1px solid #B5351B;
	}
#container, #footer {
width: 770px;
}
#container, #footer {
margin: 0 auto 10px auto;
}
#container {
position: relative;
text-align: left;
-webkit-box-shadow: rgba(0, 0, 0, 0.2) 0px 0px 5px;
-moz-box-shadow: rgba(0,0,0,0.2) 0px 0px 5px;
-o-box-shadow: rgba(0,0,0,0.2) 0px 0px 5px;
box-shadow: rgba(0, 0, 0, 0.2) 0px 0px 5px;
}
.clearfix[class], #stage[id] {
display: block;
}
#stage {
padding: 30px 28px 5px 28px;
background: none;
border: none;
}
.clearfix::after, #stage::after {
clear: both;
content: ".";
display: block;
height: 0;
visibility: hidden;
}
#container {
color: #fff;
}
#container {
text-align: left;
}
#main {
float: none;
border: 1px dashed #D87E3E;
background: #797979;
text-align: center;
}
.footer {
width: auto;
margin: 0 28px 0 28px;
clear: left;
line-height: 1.3em;
padding: 15px 0 15px 0;
}
.footer h1 {
float: right;
margin: -4px 0px 0 0;
}
h1.logo {
font-size: 100%;
text-indent: -9000px;
text-decoration: none;
}	
.footer p {
margin: 0 5px;
font-weight: bold;
color: #FFF;
}
#error .footer a {
font-size: 85%;
color: #fff;
}
.footer p, .footer .links {
margin: 0 5px;
font-weight: bold;
text-shadow: rgba(0, 0, 0, 0.3) 1px 1px 1px;
}

</style>
</head>

<body id="error">

	
<div id="container">
		
	<div id="stage">
		
		<div id="main">
			<img style="padding-top:5px;" src="../../resources/images/logo-mail.png" />
			<h2>Mmm.. parece que acá no es donde querías llegar...</h2>
			<img style="border:2px dotted black;margin-bottom:10px;" src="../../resources/images/ovejas.jpg" height="250" width="500" alt="404 kuesty" />
		</div><!--main-->

	</div><!--stage-->
	
	<div class="footer">
		<h1 class="logo"><a href="/">Kuesty</a></h1>
		<p><strong>Kuesty</strong>. Sabés a donde ir.</p><br>
		<p>
		<a href="/">Home</a> | 
		<a href="/restaurants">Restaurants</a> | 
		<a href="/mobile">Mobile</a>
		</p>
	</div>
		
</div><!--container-->

</body>
</html>
