
	<div id="marginador_centro">
  <div id="titulo_categoria">
    <div id="titulo_seccion"><h1><?php echo $this->title ?></h1></div>
    </div>
         

			<div class="form_new">
            
            <div id='preview'></div>
			
            </div>


			<?php if ($this->msg ){ ?>	<h2>Los datos han sido guardados con exito</h2>	<?php } ?>
			<div id="form" style="text-align:center;">
                            <?=$this->form ?>

            </div>
             </div>
                        
				<a href="/barra/<?php echo $this->module ?>" class="button volver-forms"> Volver</a>

		 </div>

<script type="text/javascript">

 	$("#fecha_ini, #fecha_fin").datepicker({dateFormat: 'yy-mm-dd'});

</script>

