<?php include('modulos/cabecera.phtml') ?>

<?php include('modulos/menu.phtml') ?>




<div id="wpbody-content">

<div class="wrap">
	<div id="icon-index" class="icon32"><br /></div>
<h2>Exportar base de datos</h2>

<div id="dashboard-widgets-wrap">

	<div id="dashboard-widgets" class="metabox-holder">
		<div class='postbox-container' style='width:49%;'>
			<div id="normal-sortables" class="meta-box-sortables">
				<div id="dashboard_right_now" class="postbox " >
				<h3 class='hndle'><span>DB name: "prolab"</span></h3>
				
				<div class="inside">
                    
                    <div class="table table_content">
                        <table>
                            <tr>
                                <td class="title">
                                    <span>prolab.sql</span>
                                    <p class="textright" style="position:relative;top:-10px;float:right;">
                                        <a href="/backend/export?sql=1" class="button">Exportar</a>
                                    </p>
                                </td>
                            </tr>
                        </table>
                    </div>

                    <div class="versions"><br class="clear" /></div>
                </div>
                
            </div>
		
            </div>
        </div>
   </div>




<div class="clear"></div>
</div><!-- dashboard-widgets-wrap -->

</div><!-- wrap -->


<div class="clear"></div></div><!-- wpbody-content -->
<div class="clear"></div></div><!-- wpbody -->
<div class="clear"></div></div><!-- wpcontent -->



<?php include('modulos/footer.phtml') ?>
