
<div class="main"> 
	<div class="main-wrap">
		<div class="header clear">
			<ul class="links clear">
			<li><strong>Bienvenido : <?=$this->username?></strong></li>
			<li><a href="http://www.hotelbarondelmil.com" target="_blank" ><img src="/resources/images/ico_view_24.png" alt="" class="icon" /> <span class="text">Ver el Sitio</span></a></li>
			<li><a href="/intranet/logout"><img src="/resources/images/ico_logout_24.png" alt="" class="icon" /> <span class="text">Logout</span></a></li>
			</ul>
		</div>
   
   
   <div class="page clear">
			

			<div class="main-icons clear">
				<ul class="clear">
<li><a href="/intranet/mensajes"><img src="/resources/images/ico_folder_64.png" class="icon" alt="" /><span class="text">Mensajes</span></a></li>
<li><a href="/intranet/promociones"><img src="/resources/images/ico_page_64.png" class="icon" alt="" /><span class="text">Promociones</span></a></li>
<!--
<li><a href="/intranet/productos"><img src="/resources/images/ico_picture_64.png" class="icon" alt="" /><span class="text">Productos</span></a></li>
<li><a href="/intranet/zonas"><img src="/resources/images/ico_clock_64.png" class="icon" alt="" /><span class="text">Zonas</span></a></li>
<li><a href="/intranet/localidades"><img src="/resources/images/ico_clock_64.png" class="icon" alt="" /><span class="text">Localidades</span></a></li>
-->
<li><a href="/intranet/administradores"><img src="/resources/images/ico_users_64.png" class="icon" alt="" /><span class="text">Administradores</span></a></li>
				</ul>
			</div>
