
<div id="wpbody-content">

<div class="wrap">
	<div id="icon-index" class="icon32"><br /></div>
<h2>Panel de administración de Kuesty</h2>

<div id="dashboard-widgets-wrap">

	<div id="dashboard-widgets" class="metabox-holder">
		<div class='postbox-container' style='width:49%;'>
			<div id="normal-sortables" class="meta-box-sortables">
				<div id="dashboard_right_now" class="postbox " >
					<h3 class='hndle'><span>Usuarios:</span></h3>
					<div class="inside">
						<div class="table table_content">
							<table id="estadisticas-home">
								<tr class="first"><td class="t posts" style="width:50%;"><b>Usuarios: </b></td> <td align="center"><?php echo $this->cant_usuarios; ?></td></tr>
								<tr class="last"><td class="t posts"><b>Inactivos: </b></td><td align="center"> <?php echo $this->usuarios_activos; ?></td></tr>
							</table>
						</div>
		
						<div class="versions"><br class="clear" /></div>
					</div>
				</div>
			</div>
			<div id="dashboard_right_now" class="postbox " >
				<h3 class='hndle'><span>Locales:</span></h3>

				<div class="inside">

				<div class="table table_content">
					<table id="estadisticas-home">
						<tr class="first"><td class="t posts"><b>Locales: </b></td><td align="center"><?php echo $this->cant_locales; ?></td></tr>
					</table>
				</div>

				<div class="versions"><br class="clear" /></div>
			</div>

		</div>
		<div id="dashboard_recent_comments" class="postbox " >
	
			<h3 class='hndle'><span>Estadísticas <span class="postbox-title-action"></span></span></h3>
			<div class="inside">

				<div class="table table_content">
					<!--table style="width:100%;padding-top:25px;">
						<tr><td class="title" style="width:50%;"><span>Cantidad de:</span> <p class="textright" style="position:relative;top:-10px;float:right;"><a href="/backend/tablero" class="button">Ver todos</a></p></td></tr>
                        		</table-->	
					<table id="estadisticas-home">
						<tr class="first"><td class="t posts" style="width:50%;"><b>Usuarios: </b></td> <td align="center"><?php echo $this->cant_usuarios; ?></td></tr>
                        			<tr class="first"><td class="t posts"><b>Inactivos: </b></td><td align="center"> <?php echo $this->usuarios_activos; ?></td></tr>
                        			<tr class="first"><td class="t posts"><b>Locales: </b></td><td align="center"><?php echo $this->cant_locales; ?></td></tr>
					</table>
				</div>


	</div>
</div>
<!--div id="dashboard_incoming_links" class="postbox " >
	<div class="handlediv" title="Click to toggle"><br /></div>
	<h3 class='hndle'><span>Incoming Links <span class="postbox-title-action"><a href="/wp-admin/?edit=dashboard_incoming_links#dashboard_incoming_links" class="edit-box open-box">Configure</a></span></span></h3>
	<div class="inside">
		<p class="widget-loading hide-if-no-js">Loading&#8230;</p><p class="describe hide-if-js">This widget requires JavaScript.</p></div>
	</div>
	<div id="dashboard_plugins" class="postbox " >
		<div class="handlediv" title="Click to toggle"><br /></div>
		<h3 class='hndle'><span>Plugins</span></h3>
		<div class="inside">
			<p class="widget-loading hide-if-no-js">Loading&#8230;</p><p class="describe hide-if-js">This widget requires JavaScript.</p></div>
		</div>
	</div>
</div>
<div class='postbox-container' style='width:49%;'>
	<div id="side-sortables" class="meta-box-sortables"><div id="dashboard_quick_press" class="postbox">
	<div class="handlediv" title="Click to toggle"><br /></div>
		<h3 class='hndle'><span>QuickPress</span></h3>
		<div class="inside">
			<p class="widget-loading hide-if-no-js">Loading&#8230;</p><p class="describe hide-if-js">This widget requires JavaScript.</p></div>
	</div>
	<div id="dashboard_recent_drafts" class="postbox " >
		<div class="handlediv" title="Click to toggle"><br /></div>
		<h3 class='hndle'><span>Recent Drafts</span></h3>
		<div class="inside">
			There are no drafts at the moment</div>
		</div>
<div id="dashboard_primary" class="postbox " >
<div class="handlediv" title="Click to toggle"><br /></div><h3 class='hndle'><span>WordPress Blog <span class="postbox-title-action"><a href="/wp-admin/?edit=dashboard_primary#dashboard_primary" class="edit-box open-box">Configure</a></span></span></h3>
<div class="inside">
<p class="widget-loading hide-if-no-js">Loading&#8230;</p><p class="describe hide-if-js">This widget requires JavaScript.</p></div>
</div-->

</div>	</div>




<div class="clear"></div>
</div><!-- dashboard-widgets-wrap -->

</div><!-- wrap -->


<div class="clear"></div></div><!-- wpbody-content -->
<div class="clear"></div></div><!-- wpbody -->
<div class="clear"></div></div><!-- wpcontent -->
