
<div class="main"> 
	<div class="main-wrap">
		<div class="header clear">
			<ul class="links clear">
			<li><strong>Bienvenido : <?=$this->username?></strong></li>
                        <li><a href="http://www.hotelbarondelmil.com" target="_blank"><img src="/resources/images/ico_view_24.png" alt="" class="icon" /> <span class="text">Ver el Sitio</span></a></li>
			<li><a href="/intranet/logout"><img src="/resources/images/ico_logout_24.png" alt="" class="icon" /> <span class="text">Logout</span></a></li>
			</ul>
		</div>
   
   
   <div class="page clear">
			
			

<?=$this->msg	?><br>

 <div class="content-box">
				<div class="box-header clear">
					<ul class="tabs clear">
						<li><a href="/intranet/<?=$this->module?>/edit">Nuevo Registro</a></li>
					</ul>
					
					<h2><?=ucfirst( $this->module ) ?></h2>
				</div>
				
				<div class="box-body clear">
					
				
				<div id="table">
						
					
						<form method="post" action="">
						<table>
							<thead>
								<tr>
										
									<th class="sorting" style="width: 300px; text-align:center; height:28px;">Nombre</th>
									<th class="sorting" style="width: 300px; text-align:center; height:28px;">&nbsp;</th>
									<th class="sorting" style="width: 300px; text-align:center; height:28px;">&nbsp;</th>
									<?php	if ( $this->module == 'negocios' )	{	?>
										<th class="sorting" style="width: 300px; text-align:center; height:28px;">&nbsp;</th>
									<?php	}	?>
								</tr>
							</thead>
							
							<tbody>
							<?php	if ( $this->records ) {	?>
								<?php	foreach ( $this->records as $key => $record ) {	?>
										<tr>
											<td class="sorting" style="width: 300px; text-align:center; height:28px;"><?= $record['nombre'] ?></td>
											<?php	if ( $this->module == 'negocios' )	{	?>
												<td class="sorting" style="width: 300px; text-align:center; height:28px;">
													<a href="/intranet/galeria/<?=$record['id'] ?>">Galeria</a>
												</td>
											<?php	}	?>	
											<td class="sorting" style="width: 300px; text-align:center; height:28px;">
												<a href="/intranet/<?=$this->module?>/modificar/<?=$record['id']?>">
													<img src="/resources/images/ico_edit_16.png"  alt="" title="edit" align="absmiddle" /> Modificar
												</a>
											</td>
											
											<td class="sorting" style="width: 300px; text-align:center; height:28px;">
												<div  onclick="javascript:jsform.eliminarregistro('<?=$record['id'] ?>','<?=$this->module ?>')">
													<img src="/resources/images/ico_delete_16.png" align="absmiddle" alt="" title="delete" /> Eliminar
												</div>
											</td>
										</tr>
						
									<?php	}	?>
						<?php	}	?>		
							</tbody>
						</table>
						
						<div class="tab-footer clear">
						<div class="pager fr">
								
								<span class="pages">
							 <?=$this->paginator ?>
							 </span>
								
							</div>
							
						</div>
						</form>
						
					</div>
				
				
				
				</div> <!-- end of box-body -->
			</div>
			
			<a href="#modal" class="modal-link">Open Modal</a>
<!-- MODAL WINDOW -->
<div id="modal" class="modal-window">
    <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. &nbsp;&nbsp; 
        <a onclick="$.fancybox.close();" href="javascript:;">Close</a>
    </p>
</div>

<a href="/resources/images/ico_edit_16.png"rel="group">
    <img src="/resources/images/ico_edit_16.png" alt="Envato Image" class="fr" />
</a>


				<div id="table">
				</div>
				</div>
			</div>