
<?php
    if($this->tabla == 'puestos')           $tag_id = 'id_puesto';
    if($this->tabla == 'areas')             $tag_id = 'id';
    if($this->tabla == 'indicadores')      $tag_id = 'id_indicador';
    if($this->tabla == 'objetivos_tc')     $tag_id = 'id_objetivo';
    if($this->tabla == 'actividad_emp')    $tag_id = 'id_actividad';
    if($this->tabla == 'dotacion_emp')     $tag_id = 'id_dotacion';
    if($this->tabla == 'iva_emp')           $tag_id = 'id_iva';
    if($this->tabla == 'paises')            $tag_id = 'id_pais';
    if($this->tabla == 'localidades')      $tag_id = 'id';
    if($this->tabla == 'planes')            $tag_id = 'id_plan';

?>


<div id="wpbody-content">
<div id="screen-meta">


<div class="wrap">
	<div id="icon-edit" class="icon32"><br /></div>
    <h2><?php echo ucfirst( $this->module ) ?></h2>



<ul class="subsubsub">
<li><a href='#' class="current">All <span class="count">(<?=$this->totalPages ?>)</span></a></li></ul>

<p class="search-box">
	<!--<input type="text" id="post-search-input" name="s" value="" />
	<input type="button" value="Buscar" class="button" />-->
<?php if($this->tabla != 'usuarios' && $this->tabla != 'empresas' && $this->tabla != 'proyectos' && $this->tabla != 'propuestas' && $this->tabla != 'reales_tc'){ ?>
           <a href="/barra/<?=$this->module?>/edit" class="button">Nuevo</a>
<?php } ?></p>

<div class="clear"></div>

<script type="text/javascript">
function search(form) {
	if(jQuery.trim(form.q.value) == "") {
		alert("El campo de busqueda no puede quedar vacio");
		return;
	}
	var l = "/barra/<?=$this->module?>/page/" + form.page.value + "/field/" + form.field.value + "/q/" + form.q.value;
	document.location.href = l;
}
</script>
<form method="GET">
	<input type="text" name="q" value="<?= $this->q?>" />
	<input type="hidden" name="page" value="<?= $this->page?>" />
	<select name="field">
	<?php foreach($this->fields as $key => $fieldName) { ?>
		<option value="<?= $fieldName?>" <?php if($this->f == $fieldName) echo 'selected="selected"' ?> /><?= $fieldName?></option>
	<?php } ?>	
	</select>
	<input type="button" value="Buscar" onclick="search(this.form);" />
</form>

<table class="widefat page fixed" cellspacing="0">
	<thead>
        <tr>
            <tr id="page-2" class="alternate iedit">
               <?php    if( $this->fields ) {   ?>
                    <?php   foreach( $this->fields as $key => $fieldName )  {   ?>
                <th scope="col" id="cb" class="manage-column column-cb check-column" ><?=  ucfirst( $fieldName )?></th>
                    <?php   }   ?>
                        <th scope="col" id="cb" class="manage-column column-cb check-column" >&nbsp;</th>
                        <th scope="col" id="cb" class="manage-column column-cb check-column" >&nbsp;</th>
               <?php   }   ?>
            </tr>
        </tr>
	</thead>
	<tbody>
        <?php	foreach ( $this->records as $key => $record ) {	?>
            <tr id="page-2" class="alternate iedit">
                <?php   foreach( $record as $fieldName  =>  $fieldValue )   {   ?>
                    <td scope="row" class="check-column"><?=$fieldValue ?></td>
                <?php   }   ?>
                <td><a href="/barra/<?=$this->module?>/modificar/<?=$record['id']?>">Modificar</a></td>
                <td style="color:red;">

                    <div  onclick="javascript:kuestyback.eliminarregistro('<?=$record['id'] ?>','<?=$this->module ?>')">
                            <a href="#">Eliminar</a>
                    </div>

                </td>
            </tr>
        <?php 
	} ?>

            <?=$this->paginator ?>
	</tbody>
</table>

<div id="ajax-response"></div>
<br class="clear" />
</div>


<div class="clear"></div></div><!-- wpbody-content -->
