<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"  dir="ltr" lang="en-US">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>Backend Kuesty</title>
    <link rel="shortcut icon" href="/resources/img_back/favicon.ico" />

    <!-- jQuery y UI  con sus estilos y todo-->
    <script type="text/javascript" src="/resources/js/jquery-1.4.3.min.js"></script>
    <script type="text/javascript" src="/resources/js/jquery-ui-1.8.6.custom.min.js"></script>
    <!-- Pam -->
    <script src="/resources/js/prolab.js" type="text/javascript"></script>
    <link type="text/css" rel="stylesheet" href="/resources/js/css/overcast/jquery-ui-1.8.6.custom.css" />

    <link type="text/css" rel="stylesheet" href="/resources/css/load-styles.css" />
    <link type="text/css" rel="stylesheet" href="/resources/css/back-color.css" />
    <link type="text/css" rel="stylesheet" href="/resources/css/backend.css" />
</head>

<body class="wp-admin no-js  index-php">
<div id="wpwrap">
<div id="wpcontent">
<div id="wphead">

<a href="/backend/index" title="Visit Site"><img id="header-logo" src="/resources/img_back/logo.png" alt="Kuesty" width="190" height="60" /></a>

</div>

<div id="wpbody" style="clear:both;margin:50px auto;width:300px;">

<body>

<div id="header_new_d">
	<table>
            <?php echo $this->form; ?>		
<!--	    <form id="login_admins">
		<tr><td style="width:100px;">Usuario </td><td><input type="text" id="username" /><td></tr>
                <tr><td>Contrase&ntilde;a </td><td><input type="password" id="password" /><td></tr>
                <tr><td></td><td><input type="button" id="login" onclick="prolab.adminLogin()" value="Iniciar sesi&oacute;n" ></td></tr>
	    </form>-->
	</table>
</div>


</div><!-- wpwrap -->


</body>
</html>
</body>
</html>


