<?php include('modulos/cabecera.phtml') ?>

<?php include('modulos/menu.phtml') ?>




<div id="wpbody-content">
<div id="screen-meta">

<div class="wrap">
	<div id="icon-ms-admin" class="icon32"><br /></div>
<h2>Tablero de control</h2>





    <h4>Datos del mes <?php if($this->mes ==""){echo date('m')-1;}else{echo $this->mes; }; ?>
    </h4>
    <form id="posts-filter" action="" method="post">
        Ver datos del mes: 
        <select name="mes">
            <option value="1">Enero</option>
            <option value="2">Febrero</option>
            <option value="3">Marzo</option>
            <option value="4">Abril</option>
            <option value="5">Mayo</option>
            <option value="6">Junio</option>
            <option value="7">Julio</option>
            <option value="8">Agosto</option>
            <option value="9">Septiembre</option>
            <option value="10">Octubre</option>
            <option value="11">Noviembre</option>
            <option value="12">Diciembre</option>
        </select>
        <input type="submit" value="Ver" />
    </form>

<div class="clear"></div>
<h3>Indicadores Gerenciales</h3>
<table class="widefat page fixed" cellspacing="0">
	<thead>
        <tr>
            <th scope="col" id="cb" class="manage-column column-cb check-column">Indicador</th>
            <th scope="col" id="cb" class="manage-column column-cb check-column">Valor real</th>
            <th scope="col" id="cb" class="manage-column column-cb check-column">Valor objetivo</th>
            <th scope="col" id="cb" class="manage-column column-cb check-column">Desvio</th>
            <th scope="col" id="cb" class="manage-column column-cb check-column">Resultado</th>
        </tr>
	</thead>
	<tbody>
        <?php foreach($this->indicadores_ger as $k=>$v){ ?>
            <tr id="page-2" class="alternate iedit">
                <td scope="row" class="check-column"><a href="/backend/indicadores?id=<?php echo $v["id_indicador"] ?>"><?php echo utf8_encode($v["descripcion"]) ?></a></td>
                <td scope="row" class="check-column"><?php echo $v["resultado"]; ?> %</td>
                <td scope="row" class="check-column"><?php echo $v["v_objetivo"] ?> %</td>
                <td scope="row" class="check-column"><?php echo ($v["resultado"]-$v["v_objetivo"]) ?></td>
                <td scope="row" class="check-column">
                    <img <?php if($v['relacion_obj'] == 'R > O'){
                                        if($v["resultado"] > $v["v_objetivo"]){
                                            echo 'src="../../img/ok.png"';
                                        }else{
                                            echo 'src="../../img/no.png"';
                                        }
                                     }; ?> height="30px;" />
                    </td>
            </tr>
        <?php } ?>
	</tbody>
</table>
<div class="clear"></div>
<h3>Indicadores Operativos</h3>
<table class="widefat page fixed" cellspacing="0">
	<thead>
        <tr>
            <th scope="col" id="cb" class="manage-column column-cb check-column">Indicador</th>
            <th scope="col" id="cb" class="manage-column column-cb check-column">Valor real</th>
            <th scope="col" id="cb" class="manage-column column-cb check-column">Valor objetivo</th>
            <th scope="col" id="cb" class="manage-column column-cb check-column">Desvio</th>
            <th scope="col" id="cb" class="manage-column column-cb check-column">Resultado</th>
        </tr>
	</thead>
	<tbody>
        <?php foreach($this->indicadores_ope as $k=>$v){ ?>
            <tr id="page-2" class="alternate iedit">
                <td scope="row" class="check-column"><a href="/backend/indicadores?id=<?php echo $v["id_indicador"] ?>"><?php echo utf8_encode($v["descripcion"]) ?></a></td>
                <td scope="row" class="check-column"><?php echo $v["resultado"]; ?> %</td>
                <td scope="row" class="check-column"><?php echo $v["v_objetivo"] ?> %</td>
                <td scope="row" class="check-column"><?php echo ($v["resultado"]-$v["v_objetivo"]) ?></td>
                <td scope="row" class="check-column">
                    <img <img <?php if($v['relacion_obj'] == 'R > O'){
                                        if($v["resultado"] > $v["v_objetivo"]){
                                            echo 'src="../../img/ok.png"';
                                        }else{
                                            echo 'src="../../img/no.png"';
                                        }
                                     }else{
                                            echo 'src="../../img/no.png"';
                                        }; ?> height="30px;" />
                </td>
            </tr>
        <?php } ?>
	</tbody>
</table>


<div id="ajax-response"></div>
<br class="clear" />
</div>


<div class="clear"></div></div><!-- wpbody-content -->



<?php include('modulos/footer.phtml') ?>
