<?php $i=0; foreach($this->checkins as $k=>$v){ ?>
<div style="float:left; width:350px;">
			<div class="tit-tips">

				<img  width="75px" class='avatar' src='/restaurants/avatar/id/<?php echo $v["id_local"] ?>' alt="<?php echo($v["nombre_local"]);?>" style="margin-right:15px; min-height:60px;"/>
				<a href="/restaurants/local/id/<?php echo($v["id_local"]);?>/name/<?php echo(preg_replace("/\s+/","-",$v["nombre_local"]));?>"><?php echo($v["nombre_local"]); ?></a> <br /><span> <?php echo(date("d/m/Y", strtotime($v["fecha"] .'+ 4 hours'))); ?></span></div>
            
            <div class="rank-dolar2 duplicate4">
                <span class="stars">
				<?php for($j=1; $j <= $v["rating"]; $j++) { ?>
           		<a class="active" href=""></a>
				<?php } ?>	
				<?php for($j=0; $j < (5 -$v["rating"]); $j++) { ?>
           		<a href=""></a>
				<?php } ?>
            	</span>
                <span class="dolar">
            		<?php for($j=1; $j <= $v["price"]; $j++) { ?>
            		<a class="active" href=""></a>
					<?php } ?>	
					<?php for($j=0; $j < (5 -$v["price"]); $j++) { ?>
            		<a href=""></a>
					<?php } ?>
				</span>
                
         	</div>
            
            <p style="width:260px;"><?php echo  $v["tip"];?><br /><br /></p>
            
            <div class="clearer"></div>
            
            <!-- div class="happy-face"><span></span>123</div-->
            <!-- div class="sad-face"><span></span>4</div-->
            
            <!-- a class="flag" href=""><span></span>Denunciar</a-->
            
			</div>  
<?php $i++; if( ($i%2) == 0) { echo '<div class="clearer"></div> <div class="clearer separator"></div>'; } ?>
<?php } ?>
