<div class="block-large" style="background-color:#E3E3E3;">
	<h2>Genera tu password mobile!<span></span></h2>
	<p>Hola <b><?php echo $this->username; ?></b>, ya estas conectado a Kuesty via Facebook. <br />Ahora solo tienes que generar tu clave para empezar a usar Kuesty en tu smartphone.</p>
	<form class="contact-form" method="POST">
		<input type="password" name="password" value="" />
		<input type="password" name="password2" value="" />
		<?php if($this->form_error) { echo '<p style="color:red;">'.$this->form_error.'</p>'; } ?>
		<input type="submit" value="enviar" />
	</form>
</div>
