
<div class="block-large">
	<h2>Amigos de <?php echo $this->usuario["user"];?> <span>  </span></h2>
	<div class="user-info">
		<!-- img class='avatar' src='<?php echo $this->usuario["avatar"]?>' alt="kuesty" /-->
		<div id="contenedor_avatar" style="width:100px;">
			<div id="preview-img">
				<img class='avatar' src='/user/avatar/id/<?php echo $this->usuario["id"]?>' alt="kuesty" />
			</div>
		</div>
		<div style="display:none;" id="id_user"><?php echo $this->usuario["id"] ?></div> 
		<div class="info-user">
 			<?php echo $this->usuario["nombre"]." ".substr($this->usuario["apellido"],0,1);?>. 
			<span><?php echo $this->usuario["puntos"]?> puntos</span>
			<span><?php echo $this->usuario["nombre_localidad"]?>, Argentina</span>
		</div>
		<div class="links-user">
			<a class='friends'><span></span><?php echo $this->usuario["cantidad_amigos"]?> amigos</a>
			<a class='tips'><span> </span><?php echo $this->usuario["cantidad_tips"]?> tips</a>
			<a class='checkin'><span> </span><?php echo $this->usuario["cantidad_checkins"]?> checkins</a>
			<a class='review2'><span> </span><?php echo $this->usuario["cantidad_reviews"]?> rese&ntilde;as</a>
		</div>
       	<p><?php echo $this->usuario["descripcion"]?></p>    
    	<div class='clearer'></div>
	</div>

    <div class='modal friendlist'>
    	<h3>Amigos<span></span></h3>
		 
		<div>
		<br />
			<?php if($this->user_id && $this->usuario["id"] == $this->user_id) { ?>
			<div class="contact-form"><form action="/user/findfriends/" method="get">				
			<a class="fb-friends" href="/user/findfriends/?via_facebook=1">Buscar amigos de Facebook que usan Kuesty<a/>
				<input type="text" name="qf" value="Busca por nombre, usuario o email" />
				<input type="button" class="lindo-boton" value="Buscar amigos" onclick="form.submit()" /></form>
			</div>	
			<div clear="both"></div>
			<br /> 
			<?php } ?>
            <?php foreach($this->friends as $k=>$friend){ ?>
		    <div class="friendlist_friend">
			<a href='/user/id/<?php echo $friend["id"];?>/user/<?php echo $friend["user"]?>/'>
                    <img width="50px" src='/user/avatar/id/<?php echo $friend["id"]?>' />
				</a>
				<p><b><?php echo $friend["user"];?></b><br />
				<?php echo $friend["puntos"]; ?> puntos<br />
				<a class="friends"> <span></span> <?php echo $friend["cantidad_amigos"]; ?> amigos</a></p>
			</div>	
			<?php } ?>
       
        </div>
        
    </div>
    
      
    </div>

