<script>localStorage.setItem("userCheckins", 0)
	
</script>

<script type="text/javascript" src="/resources/js/jquery.form.js"></script>
<script type="text/javascript">
$(document).ready(function() 
{ 
	
	$('#photoimg').live('change', function()	
		{ 
			$("#imageform").ajaxForm(
				{
					//target: '#preview-img'
					success:function(rta){
						rta=JSON.parse(rta);
						if(rta.error){
							alert(rta.error);
						}else{
							$("#preview-img").html(rta.html);
						}
				}
				}).submit();
	});
}); 
</script>


<div class="block-large">
	<h2>Perfil de <?php echo $this->usuario["user"];?> <span>  </span></h2>
	<div class="user-info">
		<!-- img class='avatar' src='<?php echo $this->usuario["avatar"]?>' alt="kuesty" /-->
		<div id="contenedor_avatar" style="width:100px;">
			<form id="imageform" method="post" enctype="multipart/form-data" action='/ajax/uploadprofileimage'>
			<div id="change-img" onmouseover="$('#change-img').show()" onmouseout="$('#change-img').hide()" style="cursor:pointer;overflow: hidden;cursor: pointer;background-color:orange;opacity:0.8;text-align:center;width:100px;height:23px;display:none;position:absolute;">Cambiar<input style="position: relative;top: -10px;left: -15px;height: 23px;width: auto;opacity: 0;" type="file" name="photoimg" id="photoimg" /></div>
			</form>
			<div id="preview-img">
				<img class='avatar' <?php if($this->usuario["id"] == $this->session_user["id"]){ ?> onmouseover="$('#change-img').show()" onmouseout="$('#change-img').hide()" <?php } ?> src='/user/avatar/id/<?php echo $this->usuario["id"]?>' alt="kuesty" />
			</div>
		</div>
		<div style="display:none;" id="id_user"><?php echo $this->usuario["id"] ?></div> 
		<div class="info-user">
 			<?php echo $this->usuario["nombre"]." ".substr($this->usuario["apellido"],0,1);?>. 
			<span><?php echo $this->usuario["nombre_localidad"]?>, Argentina</span>
			<?php if($this->usuario["id"] == $this->session_user["id"]){ ?>
			<span><?php echo $this->usuario["puntos"];?> puntos</span><a id="puntosBtt" href="/premios" class="lindo-boton">Canjear</a>

			
			<script type="text/javascript">
/*
				guiders.createGuider({
			      attachTo: "#puntosBtt",
				  buttons: [{name: "Cerrar", onclick : guiders.hideAll }, {name: "Ver premios", onclick: function(){ document.location.href='/premios/'}}],

				  description: "Los puntos de Kuesty valen!!! Cada vez que hagas checkin, dejes un tip o escribas una reseña sobre un local vas sumando puntos que luego vas a poder canjear por premios y descuentos. Es muy facil, matematica, mas checkins o tips dejas en los locales, mas puntos juntas, mas premios vas a poder canjear. Que estas esperando para hacerlo!!!",
			      id: "second",
			      position: 3,
				  title: "Todos esos puntos tienes ? Tal vez te alcance para canjear algun premio!"
			    }).show();

				setTimeout("guiders.hideAll()", 15000);
				$("#second").find("p").css("text-align", "left");

 */
			</script> 

	
			<?php } ?>
			<?php if($this->myfriend['estado'] == 'NN'){ ?>
			<button class="lindo-boton" onclick="kuesty.addFriend(<?php echo $this->usuario['id'] ?>)">Agregar como amigo</button>
			<?php }elseif($this->myfriend['estado'] == 'P'){
					if($this->myfriend['id_user1'] == $this->session_user['id']){
						//soy yo la que mande la request
					?>
			<button class="lindo-boton" disabled="disabled" style="opacity:0.7">Solicitud pendiente</button>

					<?php	}else{ ?>			
						<button class="lindo-boton" onclick="kuesty.acceptFriend(<?php echo $this->usuario['id'] ?>)">Aceptar</button>
						<button class="lindo-boton" onclick="kuesty.rejectFriend(<?php echo $this->usuario['id'] ?>)">Rechazar</button>
					<?php }
			}elseif($this->myfriend['estado'] == 'D' && $this->myfriend['id_user1'] == $this->session_user['id']){  //si no me aceptaron ?>
				<button class="lindo-boton" disabled="disabled" style="opacity:0.7">Solicitud pendiente</button>
			<?php } ?>
		</div>
		<div class="links-user">
			<a class='friends'><span></span><?php echo $this->usuario["cantidad_amigos"]?> amigos</a>
			<a class='tips'><span> </span><?php echo $this->usuario["cantidad_tips"]?> tips</a>
			<a class='checkin'><span> </span><?php echo $this->usuario["cantidad_checkins"]?> checkins</a>
			<a class='review2'><span> </span><?php echo $this->usuario["cantidad_reviews"]?> rese&ntilde;as</a>
		</div>
       	<p><?php echo $this->usuario["descripcion"]?></p>    
    	<div class='clearer'></div>
	</div>

    <div class='modal friendslist'>
    	<h3>Amigos<span></span></h3>
		 
		
           <?php foreach($this->friends as $k=>$friend){ ?>
		    <div class="friendlist_friend">
			<a href='/user/id/<?php echo $friend["id"];?>/user/<?php echo $friend["user"];?>'>
                    <img width="50px" src='/user/avatar/id/<?php echo $friend["id"]?>' />
				</a>
				<p><b><?php echo $friend["user"];?></b><br />
				<?php echo $friend["puntos"]; ?> puntos<br />
				<a class="friends"> <span></span> <?php echo $friend["cantidad_amigos"]; ?> amigos</a></p>
			</div>	
			<?php } ?>
			<?php if(sizeof($this->friends) >= 3) { ?>
			<a href="/user/friends/id/<?php echo $this->usuario["id"]; ?>" class="vermasBtt"></a>
			<?php } ?>

    </div>
    
       
    <div class="modal checkin" id="userCheckinContainer">
   		<h5>ultimos tips<span></span></h5>
		<?php if(count($this->checkins) == '0'){
				  echo("<span class='empty-data'>El usuario no ha escrito ningún tip todav&iacute;a</span>");
				}else{
				echo $this->render("/user/checkins.phtml");
			} ?>
        
        <button class="view-more" onclick="kuesty.loadCheckinsUser()">ver más</button>
        
        <div class="clearer"></div>                         
        
    </div>
    
    
    
    <div class='modal'>
    
    	<h6>Ultimas rese&ntilde;as <span></span></h6>
        <?php if(count($this->reviews) == 0){
				  echo("<span class='empty-data'>El usuario no ha escrito ninguna rese&ntilde;a todav&iacute;a</span>");
				}else{
					foreach($this->reviews as $k=>$v){

				 ?>
        	<div class="tit-tips">
		   		<a href="/restaurants/local/id/<?php echo $v["id_local"];?>/name/<?php echo preg_replace("/\s+/","-",$v["nombre_local"]);?>"><?php echo $v["nombre_local"]?> <br />
				<span>&nbsp;</span></a>
			</div>
            
			<img src="<?php echo $v["logo"]; ?>" alt="<?php echo preg_replace("/\s+/","-",$v["nombre_local"]);?>" width="150px" height="100px" style="float:left;margin-left:25px;" />
            <div class="rank-dolar duplicate">
                 <span class="stars">
              		<?php for($j=1; $j <= $v["rating"]; $j++) { ?>
            		<a class="active" href=""></a>
					<?php } ?>	
					<?php for($j=0; $j < (5 -$v["rating"]); $j++) { ?>
            		<a href=""></a>
					<?php } ?>

				 </span>
                <span class="dolar">
  					<?php for($j=1; $j <= $v["price"]; $j++) { ?>
            		<a class="active" href=""></a>
					<?php } ?>	
					<?php for($j=0; $j < (5 -$v["price"]); $j++) { ?>
            		<a href=""></a>
					<?php } ?>

				</span>
				<br />
				<div><?php echo(date("d/m/Y", strtotime($v["fecha"] .'+ 4 hours'))); ?></div> 
         	</div>
            
            <p style="white-space:pre-line;">
				<?php echo $v["comentario"]?>
            </p>
            
            <div class="clearer"></div>
            
            <!-- div class="happy-face"><span></span>123</div-->
            <!-- div class="sad-face"><span></span>4</div -->
            
            <!-- a class="flag" href=""><span></span>Denunciar</a-->
            
            <div class="clearer separator"></div>
            <?php }} ?>
            
    
    		<!-- button class="view-more">ver más</button -->
    
    </div>

	
		
	</div>

	<div class="top-users">
    <h2>es fan de:</h2>
		<?php if(count($this->locales) == 0){ ?>
			<span style="color:#fff;font-weight:bold;padding-top:25px;padding-left:34%;">Ningún local</span>
		<?php } foreach($this->locales as $local) { ?>
		<div class="user local-fan-costado" onclick="document.location.href = '/restaurants/local/id/<?php echo($local['id']);?>/name/<?php echo(preg_replace("/\s+/","-",$local['nombre']));?>'">
    		<img src="<?php echo($local["logo_mobile"]);?>" alt="<?php echo(preg_replace("/\s+/","-",$local["nombre"]));?>" style="width:50px;min-height:50px;"/>
			<p><?php echo($local["nombre"]);?>
			<div class="rank-dolar duplicate">
				<span class="stars">
              		<?php for($j=1; $j <= $local["stars"]; $j++) { ?>
            		<a class="active" href=""></a>
					<?php } ?>	
					<?php for($j=0; $j < (5 -$local["stars"]); $j++) { ?>
            		<a href=""></a>
					<?php } ?>

				 </span>
                <span class="dolar">
  					<?php for($j=1; $j <= $local["pesos"]; $j++) { ?>
            		<a class="active" href=""></a>
					<?php } ?>	
					<?php for($j=0; $j < (5 -$local["pesos"]); $j++) { ?>
            		<a href=""></a>
					<?php } ?>
				</span>
			</div>
			</p>
    		<div class="clearer"></div>
    	</div>
    	<?php } ?>
    	
    </div>

