   <div class="block-large" style="background-color:#E3E3E3;">
    
    
    
    	<h2>Quiero iniciar sesion en Kuesty!<span></span></h2>
        
		<!--div id="fb-root"><a href="<?php echo $this->fb_login;?>"></a></div-->
		<?php if($this->fb_login_error) { ?> <p style="color:red;">Ha ocurrido un error en la autentificacion con facebook. Intente nuevamente</p><?php } ?>		

		<div class="contact-form">
        
        	<form method="POST">

            	<label>Usuario</label>
                <input type="text" name="user" value=""/><br />
                
                <label>Contrase&ntilde;a</label>
                <input type="password" name="pass" value="" /><br />
                
				<?php if($this->error) { ?>
					<p class="error"><?php echo $this->error; ?></p>
				<?php } ?>
                <input type="submit" value="Ingresar" />
                
            </form>
        
        </div>
   		
		 
        <div class="email-box">
			<br />	
        	<a href="/signup">Quiero Registrarme!</a><br/>            
			<br />	
        	<a href="/user/recover">Olvide mi contrase&ntilde;a!</a><br/>            
        </div>


    </div>

