<div class="block-large" style="background-color:#E3E3E3;">
	<h2>Genera una nueva clave<span></span></h2>
	<form class="contact-form" method="POST">
	<?php if(!$this->form_error){ ?>
		<label>Nueva contraseña</label>
		<input type="password" name="password" value="" />
		<label>Repite nueva contraseña</label>
		<input type="password" name="password2" value="" />
		<input type="submit" value="enviar" />
		<?php if($this->error) { echo '<p style="color:red;">'.$this->error.'</p>'; } ?>
		<?php } ?>
		<?php if($this->form_error) { echo '<p style="color:red;">'.$this->form_error.'</p>'; } ?>
	</form>
</div>
