
<div class="block-large">
	<h2>Notificaciones de <?php echo $this->usuario["user"];?> <span>  </span></h2>
	<div class="user-info">
		<!-- img class='avatar' src='<?php echo $this->usuario["avatar"]?>' alt="kuesty" /-->
		<div id="contenedor_avatar" style="width:100px;">
			<div id="preview-img">
				<img class='avatar' src='/user/avatar/id/<?php echo $this->usuario["id"]?>' alt="kuesty" />
			</div>
		</div>
		<div style="display:none;" id="id_user"><?php echo $this->usuario["id"] ?></div> 
		<div class="info-user">
 			<?php echo $this->usuario["nombre"]." ".substr($this->usuario["apellido"],0,1);?>. 
			<span><?php echo $this->usuario["puntos"]?> puntos</span>
			<span><?php echo $this->usuario["nombre_localidad"]?>, Argentina</span>
		</div>
		<div class="links-user">
			<a class='friends'><span></span><?php echo $this->usuario["cantidad_amigos"]?> amigos</a>
			<a class='tips'><span> </span><?php echo $this->usuario["cantidad_tips"]?> tips</a>
			<a class='checkin'><span> </span><?php echo $this->usuario["cantidad_checkins"]?> checkins</a>
			<a class='review2'><span> </span><?php echo $this->usuario["cantidad_reviews"]?> rese&ntilde;as</a>
		</div>
       	<p><?php echo $this->usuario["descripcion"]?></p>    
    	<div class='clearer'></div>
	</div>

    <div class='modal notificaciones'>
    	<h3>Notificaciones<span></span></h3>
		 
		<div>
		<br />
			<!-- 
			// solicitud de amistad 
		    <div class="notif">
				<a href="/user/?id=1">picapiedra</a> quiere ser tu amigo
			</div>
			// share local 
		    <div class="notif">
				<a href="/user/?id=1">picapiedra</a> te recomienda el local <a href="/restaurants/local/?id=1">Ming Fat Food</a>
			</div>
			// acepto amistad 
		    <div class="notif">
				<a href="/user/?id=1">lisso5</a> te ha aceptado como amigo. Hurra!
			</div>
			-->
            <?php foreach($this->notificaciones as $k=>$notif){ ?>
			<?php if($notif["mensaje_web"] == "" || !$notif["mensaje_web_fixed"]){ continue; } ?>
			<?php $notif["mensaje_web"] = preg_replace("/@([\w\d]+)/i",'<a href="http://twitter.com/$0" target="_blank">$0</a>', $notif["mensaje_web"]); ?>
			<div class="notif">
				<?php echo $notif["mensaje_web"]; ?>
			</div>	
			<?php } ?>
       
        </div>
        
    </div>
    
      
    </div>

