		<?php $this->render("/modules/search.phtml") ?>
		<div id="contenido">
	        <div class="left">
		        <div class="restaurants">
	                <div class="content_user">
						<div class="photo_user">
            	        	<img src="<?php if(file_exists("/resources/avatars/".$this->usuario['id']."/".md5($this->usuario['id'])."_s.jpg")){
								echo("/resources/avatars/".$this->usuario['id']."/".md5($this->usuario['id'])."_s.jpg");
							}else{
								echo("/resources/img_example/user.png");
							} ?>" border="0"/>
                    	</div>
                    	<div class="datos">
							<h2><?php echo($this->usuario["nombre"]." ".$this->usuario["apellido"]); ?></h2>
                        	<p><?php echo($this->usuario["nombre_prov"].", ".$this->usuario["nombre_localidad"]) ?> </p>
                        	<p>Amigos: <font><?php echo($this->usuario["cantidad_amigos"]); ?></font></p>
                        	<p>Reseñas: <font><?php echo($this->usuario["cantidad_reviews"]); ?></font></p>
                        	<p>Checkins: <font><?php echo($this->usuario["cantidad_checkins"]); ?></font></p>
                    	</div>
                    	<br clear="all"/>
						<?php if($this->friends["estado"] == "P" || $this->friends["estado"] == "D"){ ?>
									<button>ya le mandaste</button>
								<?php 	}elseif($this->friends == "NN"){ ?>
		                    		<button class="add" onclick="kuesty.addFriend(<?php echo $this->usuario["id"] ?>,this)">+agregar</button>
						<?php    } if($this->friends["estado"] == "A") $isFriend = 1; else $isFriend=0; ?>
                    	<h2>Sobre mi</h2>
						<div id="descripcion_usr">
						<p>
						<?php if($this->usuario["descripcion"] == ""){
							echo($this->usuario["nombre"]." se ha unido a Kuesty el ".date('d/m/Y', strtotime($this->usuario['fecha_ingreso']) ));
						}else{
							echo($this->usuario["descripcion"]);
						} ?>
						</p>
						</div>
                    	<div id="user_tabs">
							<ul>
								<li><a href="#tabs-1">Reseñas</a></li>
								<?php if($isFriend == 1){ ?><li><a href="#tabs-2">Tips</a></li><?php }?>
							</ul>
							<div id="tabs-1">
		                    	<hr />
        			            	<h2><b>Reseñas </b> de <?php echo($this->usuario["nombre"]); ?></h2>
                    			<hr />
								<?php 
								if(count($this->reviews) == 0){
									echo "<div id='no_reviews' style='color:#505050'>".$this->usuario["nombre"]." no ha escrito ninguna reseña todavía...</div>";
								}else{
									foreach($this->reviews as $k=>$v){ ?>

										<div class="modulo_reviews_resto">
										<div class="user_reviews">
										    <div class="img"><img src='<?php if(file_exists('/resources/locales/thumb_.$v["id_local"]._m.png')) {
																echo('/resources/locales/thumb_.$v["id_local"]._m.png');
															}else{
																echo('/resources/images/default_local.png');
															}
													?>' height="100px" /></div>
										    <p class="gris"><b><?php echo $v['nombre_local'] ?></b></p>
										    <br clear="all" />
										</div>
										<div class="reviews_resto_user">
											 <div class="rate rate_">
											<?php 
												for( $star=1; $star<=5; $star++ ){ 
													$starsToShow = ( $star <= $v['rating'] ) ? '<a class="activa"></a>' : '<a></a>' ;
													echo $starsToShow;
												} 
											?>
										        <br clear="all" />
										    </div>
										    <div class="rate rate_ pesos_">
											<?php 
												for( $pesos=1; $pesos<=5; $pesos++ ){ 
													$pricesToShow = ( $pesos <= $v['price'] ) ? '<a class="activa"></a>' : '<a></a>' ;
													echo $pricesToShow;
												} 
											?>
										        <br clear="all" />
										    </div>
										    <div class="fecha_restaurant"><?php echo date('d/m/Y', strtotime($v['fecha']) ) ?></div>
										    <br clear="all" />
										    <p class="gris"><i><?php echo $v['comentario']?> </i></p>
										</div>
										<br clear="all" />
										<div class="gusto-nogusto">
										    <div style="width:60px;"><button id="likes_<?php echo $v["id"]?>" onclick="kuesty.likeReview(<?php echo $v["id"].",1" ?>)" class="ok"><?php echo $v['likes']?></button><div><?php echo $v['likes']?></div></div>
										    <div style="width:60px;"><button id="unlikes_<?php echo $v["id"]?>" onclick="kuesty.likeReview(<?php echo $v["id"].",0" ?>)" class="nok"><?php echo $v['unlikes']?></button><div><?php echo $v['unlikes']?></div></div>

										    <br clear="all"/>
										</div>      
									</div>

								<?php } ?>
								<?php }?>
							</div>
							<!-- fin tabs-1 -->
							<?php if($isFriend == 1){ ?>
							<div id="tabs-2">
								<hr />
        			            	<h2><b>Tips </b> de <?php echo($this->usuario["nombre"]); ?></h2>
                    			<hr />
								<?php 
								if(count($this->tips) == 0){
									echo "<div id='no_reviews' style='color:#505050'>".$this->usuario["nombre"]." no ha escrito ningún tip todavía...</div>";
								}else{
									foreach($this->tips as $k=>$v){ ?>
						            <div class="post_user_review">
							            <div class="resto_thumb">
											<img src='<?php if(file_exists('/resources/locales/thumb_.$v["id_local"]._m.png')) {
																echo('/resources/locales/thumb_.$v["id_local"]._m.png');
															}else{
																echo('/resources/images/default_local.png');
															}
													?>' height="80px" />
											<p><?php echo $v["nombre_local"] ?></p>
					                	</div>
					                	<div class="resto_text">
					                        <div class="rate">
											<?php 
												for( $star=1; $star<=5; $star++ ){ 
													$starsToShow = ( $star <= $v['rating'] ) ? '<a class="activa"></a>' : '<a></a>' ;
													echo $starsToShow;
												} 
											?>
				                     	       <br clear="all"/>
				                       	 	</div>
				                        	<div class="fecha"><?php echo date('d/m/Y', strtotime($v['fecha']) ) ?></div>
				                        	<br clear="both" />
				                        	<p>
												<?php echo $v["tip"] ?>
											</p>
										</div>
										<div onclick="kuesty.flagCheckin(<?php echo $v["id"] ?>,this)">Denunciar</div>
				                    	<br clear="all" />
									</div>
								<?php }} ?>
							</div>
							<!-- fin tabs-2 -->
							<?php } ?>
						</div>
						<!-- fin user-tabs -->
                       
	                </div>
                </div>
            </div>
            <br clear="all" />
        </div>
