<?php 
	foreach($this->comunidad as $evento) { 
		$date = $evento["fecha"];
		$date = date('Y-m-d G:i:s', strtotime($date . ' + 4 hours'));	
		$evento["fecha"] = $date;
		$evento["post"]  = preg_replace("/@([\w\d]+)/i",'<a href="http://twitter.com/$0" target="_blank">$0</a>', $evento["post"]);
	?>
	<div class="comunidad_event"> 
		<?php if($evento["tipo"] == "newlocalbyuser") { ?>
			<a class="user_logo" onclick="kuesty.loadFriend(<?php echo $evento["id_user"];?>)">
				<img width="75px" src="/user/avatar/id/<?php echo $evento["id_user"];?>" />
			</a>
			<a onclick="kuesty.loadFriend(<?php echo $evento["id_user"];?>)"><?php echo $evento["nom_user"];?></a> ha agregado el local 
			<a onclick="kuesty.loadLocal(<?php echo $evento["id_local"];?>)"><?php echo $evento["nom_local"];?></a> a kuesty
			<span><?php echo My_Utils::ago($evento['fecha_server']); ?></span><br />	
			<a class="local_logo" onclick="kuesty.loadLocal(<?php echo $evento["id_local"];?>)">
				<img width="200px" src="/restaurants/avatar/id/<?php echo $evento["id_local"];?>" />
			</a>

		<?php }elseif($evento["tipo"] == "newuser") { ?>
			<a onclick="kuesty.loadFriend(<?php echo $evento["id_user"];?>)"><?php echo $evento["nom_user"];?></a> se ha unido a kuesty
			<span><?php echo My_Utils::ago($evento['fecha_server']); ?></span><br />	
			<a class="friend_logo" onclick="kuesty.loadFriend(<?php echo $evento["id_user"];?>)">
				<img width="100px" src="/user/avatar/id/<?php echo $evento["id_user"];?>" />
			</a>


		<?php } elseif($evento["tipo"] == "promo_unlock") { ?>

		<a class="user_logo" onclick="kuesty.loadFriend(<?php echo $evento["id_user"];?>)">
			<img width="75px" src="/user/avatar/id/<?php echo $evento["id_user"];?>" />
		</a>

		<a onclick="kuesty.loadFriend(<?php echo $evento["id_user"];?>)"><?php echo $evento["nom_user"];?></a> 
		ha desbloqueado una promocion en <a onclick="kuesty.loadLocal(<?php echo $evento["id_local"];?>)"><?php echo $evento["nom_local"];?></a>

		<a onclick="kuesty.loadLocal(<?php echo $evento["id_local"];?>)"><?php echo $evento["nom_local"];?></a>
		<span><?php echo My_Utils::ago($evento['fecha_server']); ?></span><br />		
		<a class="local_logo" onclick="kuesty.loadLocal(<?php echo $evento["id_local"];?>)">
			<img width="200px" src="/restaurants/avatar/id/<?php echo $evento["id_local"];?>" />
		</a>

		<p style="width:500px;"><?php echo $evento["post"]; ?></p>


		<?php }elseif($evento["tipo"] == "newcheckin" || $evento["tipo"] == "newreview") { ?>
			
			<a class="user_logo" onclick="kuesty.loadFriend(<?php echo $evento["id_user"];?>)">
				<img width="75px" src="/user/avatar/id/<?php echo $evento["id_user"];?>" />
			</a>
			<a onclick="kuesty.loadFriend(<?php echo $evento["id_user"];?>)"><?php echo $evento["nom_user"];?></a> 
			<?php if($evento["tipo"] == "newcheckin") { ?> ha hecho checkin en <?php } else { ?> ha escrito una rese&ntilde;a sobre <?php } ?>
			<a onclick="kuesty.loadLocal(<?php echo $evento["id_local"];?>)"><?php echo $evento["nom_local"];?></a>
			<span><?php echo My_Utils::ago($evento['fecha_server']); ?></span><br />		
			<a class="local_logo" onclick="kuesty.loadLocal(<?php echo $evento["id_local"];?>)">
				<img width="200px" src="/restaurants/avatar/id/<?php echo $evento["id_local"];?>" />
			</a>

			<div style="float:none;" class="float-star">
                 <span class="stars">
					<?php for($j=1; $j <= $evento["stars"]; $j++) { ?>
            		<a class="active" href=""></a>
					<?php } ?>	
					<?php for($j=0; $j < (5 -$evento["stars"]); $j++) { ?>
            		<a href=""></a>
					<?php } ?>
            	</span>
            </div>
            <div style="float:none;" class="float-star">
                <span class="dolar">
            		<?php for($j=1; $j <= $evento["pesos"]; $j++) { ?>
            		<a class="active" href=""></a>
					<?php } ?>	
					<?php for($j=0; $j < (5 -$evento["pesos"]); $j++) { ?>
            		<a href=""></a>
					<?php } ?>
            	</span>
            </div>

			<p style="width:500px;"><?php echo $evento["post"]; ?><?php if($evento["tipo"] == "newreview") { ?>
	<a href="/restaurants/local/id/<?php echo $evento["id_local"];?>/name/<?php echo $evento["nom_local"];?>/rid/<?php echo $evento["id_review"];?>">
					Ver critica completa
					</a><?php } ?>
			</p>

		<?php }elseif($evento["tipo"] == "friendship") { ?>
		<?php 
			if($this->filter == "me" && $evento["id_friend"] == $this->mid) { 
				$aux["id"] = $evento["id_user"];
				$aux["nom"] = $evento["nom_user"];

				$evento["id_user"] = $evento["id_friend"];
				$evento["nom_user"] = $evento["nom_friend"];
			
				$evento["id_friend"] = $aux["id"];
				$evento["nom_friend"] = $aux["nom"];

			}
			if($this->filter == "friends" && $evento["id_user"] == $this->mid) { 

				$aux["id"] = $evento["id_user"];
				$aux["nom"] = $evento["nom_user"];

				$evento["id_user"] = $evento["id_friend"];
				$evento["nom_user"] = $evento["nom_friend"];
			
				$evento["id_friend"] = $aux["id"];
				$evento["nom_friend"] = $aux["nom"];

			}
			?>

			<a class="user_logo" onclick="kuesty.loadFriend(<?php echo $evento["id_user"];?>)">
				<img width="75px" src="/user/avatar/id/<?php echo $evento["id_user"];?>" />
			</a>
			<a onclick="kuesty.loadFriend(<?php echo $evento["id_user"];?>)"><?php echo $evento["nom_user"];?></a> ahora es amigo de 
			<a onclick="kuesty.loadFriend(<?php echo $evento["id_friend"];?>)"><?php echo $evento["nom_friend"];?></a>
			<span><?php echo My_Utils::ago($evento['fecha_server']); ?></span><br />	
			<a class="friend_logo" onclick="kuesty.loadFriend(<?php echo $evento["id_friend"];?>)">
				<img width="100px" src="/user/avatar/id/<?php echo $evento["id_friend"];?>" />
			</a>

		<?php }elseif($evento["tipo"] == "newfan") { ?>
			<a class="user_logo" onclick="kuesty.loadFriend(<?php echo $evento["id_user"];?>)">
				<img width="75px" src="/user/avatar/id/<?php echo $evento["id_user"];?>" />
			</a>
			<a onclick="kuesty.loadFriend(<?php echo $evento["id_user"];?>)"><?php echo $evento["nom_user"];?></a> se ha hecho fan de 
			<a onclick="kuesty.loadLocal(<?php echo $evento["id_local"];?>)"><?php echo $evento["nom_local"];?></a>
			<span><?php echo My_Utils::ago($evento['fecha_server']); ?></span><br />	
			<a class="local_logo" onclick="kuesty.loadLocal(<?php echo $evento["id_local"];?>)">
				<img width="200px" src="/restaurants/avatar/id/<?php echo $evento["id_local"];?>" />
			</a>

		<?php }elseif($evento["tipo"] == "newlocalstatus") { ?>

			<?php if( trim($evento["post"]) == "") {
				continue;
			} ?>
			<a class="user_logo" onclick="kuesty.loadLocal(<?php echo $evento["id_local"];?>)">
				<img width="75px" src="/restaurants/avatar/id/<?php echo $evento["id_local"];?>/mobile/1" />
			</a>
			<a onclick="kuesty.loadLocal(<?php echo $evento["id_local"];?>)"><?php echo $evento["nom_local"];?></a> ha actualizado su estado 
			<span><?php echo My_Utils::ago($evento['fecha_server']); ?></span><br />	
			<p style="width:530px">&ldquo;<?php echo $evento["post"]; ?>&rdquo;</p>

		<?php }else if($evento["tipo"] == "checkin_especial"){ ?>
	
			<a class="user_logo" onclick="kuesty.loadLocal(<?php echo $evento["id_local"];?>)">
				<img width="75px" src="/restaurants/avatar/id/<?php echo $evento["id_local"];?>/mobile/1" />
			</a>
			<a onclick="kuesty.loadLocal(<?php echo $evento["id_local"];?>)"><?php echo $evento["nombre_local"];?></a> creo un checkin especial 
			<span><?php echo My_Utils::ago($evento['fecha_creacion']); ?></span><br />	
			<p style="width:530px">&ldquo;<?php echo $evento["descripcion"]; ?>&rdquo;</p>


		<?php } ?>
	</div>
	<div class="clearer"></div>
	<?php } ?>

